// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct BrainData {
  uint32 traitA;
  uint32 traitB;
  uint32 traitC;
  uint32 traitD;
}

library Brain {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "ratroom", name: "Brain", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x7462726174726f6f6d00000000000000427261696e0000000000000000000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0010040004040404000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (bytes32)
  Schema constant _keySchema = Schema.wrap(0x002001005f000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint32, uint32, uint32, uint32)
  Schema constant _valueSchema = Schema.wrap(0x0010040003030303000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "playerId";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](4);
    fieldNames[0] = "traitA";
    fieldNames[1] = "traitB";
    fieldNames[2] = "traitC";
    fieldNames[3] = "traitD";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get traitA.
   */
  function getTraitA(bytes32 playerId) internal view returns (uint32 traitA) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get traitA.
   */
  function _getTraitA(bytes32 playerId) internal view returns (uint32 traitA) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set traitA.
   */
  function setTraitA(bytes32 playerId, uint32 traitA) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((traitA)), _fieldLayout);
  }

  /**
   * @notice Set traitA.
   */
  function _setTraitA(bytes32 playerId, uint32 traitA) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((traitA)), _fieldLayout);
  }

  /**
   * @notice Get traitB.
   */
  function getTraitB(bytes32 playerId) internal view returns (uint32 traitB) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get traitB.
   */
  function _getTraitB(bytes32 playerId) internal view returns (uint32 traitB) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set traitB.
   */
  function setTraitB(bytes32 playerId, uint32 traitB) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((traitB)), _fieldLayout);
  }

  /**
   * @notice Set traitB.
   */
  function _setTraitB(bytes32 playerId, uint32 traitB) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((traitB)), _fieldLayout);
  }

  /**
   * @notice Get traitC.
   */
  function getTraitC(bytes32 playerId) internal view returns (uint32 traitC) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get traitC.
   */
  function _getTraitC(bytes32 playerId) internal view returns (uint32 traitC) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set traitC.
   */
  function setTraitC(bytes32 playerId, uint32 traitC) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((traitC)), _fieldLayout);
  }

  /**
   * @notice Set traitC.
   */
  function _setTraitC(bytes32 playerId, uint32 traitC) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((traitC)), _fieldLayout);
  }

  /**
   * @notice Get traitD.
   */
  function getTraitD(bytes32 playerId) internal view returns (uint32 traitD) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get traitD.
   */
  function _getTraitD(bytes32 playerId) internal view returns (uint32 traitD) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set traitD.
   */
  function setTraitD(bytes32 playerId, uint32 traitD) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((traitD)), _fieldLayout);
  }

  /**
   * @notice Set traitD.
   */
  function _setTraitD(bytes32 playerId, uint32 traitD) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((traitD)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get(bytes32 playerId) internal view returns (BrainData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(bytes32 playerId) internal view returns (BrainData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(bytes32 playerId, uint32 traitA, uint32 traitB, uint32 traitC, uint32 traitD) internal {
    bytes memory _staticData = encodeStatic(traitA, traitB, traitC, traitD);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(bytes32 playerId, uint32 traitA, uint32 traitB, uint32 traitC, uint32 traitD) internal {
    bytes memory _staticData = encodeStatic(traitA, traitB, traitC, traitD);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(bytes32 playerId, BrainData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.traitA, _table.traitB, _table.traitC, _table.traitD);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(bytes32 playerId, BrainData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.traitA, _table.traitB, _table.traitC, _table.traitD);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  ) internal pure returns (uint32 traitA, uint32 traitB, uint32 traitC, uint32 traitD) {
    traitA = (uint32(Bytes.getBytes4(_blob, 0)));

    traitB = (uint32(Bytes.getBytes4(_blob, 4)));

    traitC = (uint32(Bytes.getBytes4(_blob, 8)));

    traitD = (uint32(Bytes.getBytes4(_blob, 12)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (BrainData memory _table) {
    (_table.traitA, _table.traitB, _table.traitC, _table.traitD) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(bytes32 playerId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(bytes32 playerId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    uint32 traitA,
    uint32 traitB,
    uint32 traitC,
    uint32 traitD
  ) internal pure returns (bytes memory) {
    return abi.encodePacked(traitA, traitB, traitC, traitD);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    uint32 traitA,
    uint32 traitB,
    uint32 traitC,
    uint32 traitD
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(traitA, traitB, traitC, traitD);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(bytes32 playerId) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = playerId;

    return _keyTuple;
  }
}
