// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct ExternalAddressesConfigData {
  address erc20Address;
  address gamePoolAddress;
  address mainSaleAddress;
  address serviceAddress;
}

library ExternalAddressesConfig {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "ratfun", name: "ExternalAddresse", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x746272617466756e000000000000000045787465726e616c4164647265737365);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0050040014141414000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of ()
  Schema constant _keySchema = Schema.wrap(0x0000000000000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (address, address, address, address)
  Schema constant _valueSchema = Schema.wrap(0x0050040061616161000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](0);
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](4);
    fieldNames[0] = "erc20Address";
    fieldNames[1] = "gamePoolAddress";
    fieldNames[2] = "mainSaleAddress";
    fieldNames[3] = "serviceAddress";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get erc20Address.
   */
  function getErc20Address() internal view returns (address erc20Address) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Get erc20Address.
   */
  function _getErc20Address() internal view returns (address erc20Address) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Set erc20Address.
   */
  function setErc20Address(address erc20Address) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((erc20Address)), _fieldLayout);
  }

  /**
   * @notice Set erc20Address.
   */
  function _setErc20Address(address erc20Address) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((erc20Address)), _fieldLayout);
  }

  /**
   * @notice Get gamePoolAddress.
   */
  function getGamePoolAddress() internal view returns (address gamePoolAddress) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Get gamePoolAddress.
   */
  function _getGamePoolAddress() internal view returns (address gamePoolAddress) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Set gamePoolAddress.
   */
  function setGamePoolAddress(address gamePoolAddress) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((gamePoolAddress)), _fieldLayout);
  }

  /**
   * @notice Set gamePoolAddress.
   */
  function _setGamePoolAddress(address gamePoolAddress) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((gamePoolAddress)), _fieldLayout);
  }

  /**
   * @notice Get mainSaleAddress.
   */
  function getMainSaleAddress() internal view returns (address mainSaleAddress) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Get mainSaleAddress.
   */
  function _getMainSaleAddress() internal view returns (address mainSaleAddress) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Set mainSaleAddress.
   */
  function setMainSaleAddress(address mainSaleAddress) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((mainSaleAddress)), _fieldLayout);
  }

  /**
   * @notice Set mainSaleAddress.
   */
  function _setMainSaleAddress(address mainSaleAddress) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((mainSaleAddress)), _fieldLayout);
  }

  /**
   * @notice Get serviceAddress.
   */
  function getServiceAddress() internal view returns (address serviceAddress) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Get serviceAddress.
   */
  function _getServiceAddress() internal view returns (address serviceAddress) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Set serviceAddress.
   */
  function setServiceAddress(address serviceAddress) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((serviceAddress)), _fieldLayout);
  }

  /**
   * @notice Set serviceAddress.
   */
  function _setServiceAddress(address serviceAddress) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((serviceAddress)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get() internal view returns (ExternalAddressesConfigData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get() internal view returns (ExternalAddressesConfigData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    address erc20Address,
    address gamePoolAddress,
    address mainSaleAddress,
    address serviceAddress
  ) internal {
    bytes memory _staticData = encodeStatic(erc20Address, gamePoolAddress, mainSaleAddress, serviceAddress);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    address erc20Address,
    address gamePoolAddress,
    address mainSaleAddress,
    address serviceAddress
  ) internal {
    bytes memory _staticData = encodeStatic(erc20Address, gamePoolAddress, mainSaleAddress, serviceAddress);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(ExternalAddressesConfigData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.erc20Address,
      _table.gamePoolAddress,
      _table.mainSaleAddress,
      _table.serviceAddress
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(ExternalAddressesConfigData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.erc20Address,
      _table.gamePoolAddress,
      _table.mainSaleAddress,
      _table.serviceAddress
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  )
    internal
    pure
    returns (address erc20Address, address gamePoolAddress, address mainSaleAddress, address serviceAddress)
  {
    erc20Address = (address(Bytes.getBytes20(_blob, 0)));

    gamePoolAddress = (address(Bytes.getBytes20(_blob, 20)));

    mainSaleAddress = (address(Bytes.getBytes20(_blob, 40)));

    serviceAddress = (address(Bytes.getBytes20(_blob, 60)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (ExternalAddressesConfigData memory _table) {
    (_table.erc20Address, _table.gamePoolAddress, _table.mainSaleAddress, _table.serviceAddress) = decodeStatic(
      _staticData
    );
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord() internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord() internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    address erc20Address,
    address gamePoolAddress,
    address mainSaleAddress,
    address serviceAddress
  ) internal pure returns (bytes memory) {
    return abi.encodePacked(erc20Address, gamePoolAddress, mainSaleAddress, serviceAddress);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    address erc20Address,
    address gamePoolAddress,
    address mainSaleAddress,
    address serviceAddress
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(erc20Address, gamePoolAddress, mainSaleAddress, serviceAddress);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple() internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    return _keyTuple;
  }
}
