// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct GameConfigData {
  address adminAddress;
  bytes32 adminId;
  uint256 globalRoomIndex;
  uint256 globalRatIndex;
  uint256 ratCreationCost;
  uint256 roomCreationCost;
  uint32 maxInventorySize;
  uint32 maxTraitsSize;
  uint32 minRoomPromptLength;
  uint32 maxRoomPromptLength;
  uint32 cooldownCloseRoom;
  uint32 cooldownReenterRoom;
}

library GameConfig {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "ratroom", name: "GameConfig", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x7462726174726f6f6d0000000000000047616d65436f6e666967000000000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x00cc0c0014202020202004040404040400000000000000000000000000000000);

  // Hex-encoded key schema of ()
  Schema constant _keySchema = Schema.wrap(0x0000000000000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (address, bytes32, uint256, uint256, uint256, uint256, uint32, uint32, uint32, uint32, uint32, uint32)
  Schema constant _valueSchema = Schema.wrap(0x00cc0c00615f1f1f1f1f03030303030300000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](0);
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](12);
    fieldNames[0] = "adminAddress";
    fieldNames[1] = "adminId";
    fieldNames[2] = "globalRoomIndex";
    fieldNames[3] = "globalRatIndex";
    fieldNames[4] = "ratCreationCost";
    fieldNames[5] = "roomCreationCost";
    fieldNames[6] = "maxInventorySize";
    fieldNames[7] = "maxTraitsSize";
    fieldNames[8] = "minRoomPromptLength";
    fieldNames[9] = "maxRoomPromptLength";
    fieldNames[10] = "cooldownCloseRoom";
    fieldNames[11] = "cooldownReenterRoom";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get adminAddress.
   */
  function getAdminAddress() internal view returns (address adminAddress) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Get adminAddress.
   */
  function _getAdminAddress() internal view returns (address adminAddress) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Set adminAddress.
   */
  function setAdminAddress(address adminAddress) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((adminAddress)), _fieldLayout);
  }

  /**
   * @notice Set adminAddress.
   */
  function _setAdminAddress(address adminAddress) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((adminAddress)), _fieldLayout);
  }

  /**
   * @notice Get adminId.
   */
  function getAdminId() internal view returns (bytes32 adminId) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (bytes32(_blob));
  }

  /**
   * @notice Get adminId.
   */
  function _getAdminId() internal view returns (bytes32 adminId) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (bytes32(_blob));
  }

  /**
   * @notice Set adminId.
   */
  function setAdminId(bytes32 adminId) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((adminId)), _fieldLayout);
  }

  /**
   * @notice Set adminId.
   */
  function _setAdminId(bytes32 adminId) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((adminId)), _fieldLayout);
  }

  /**
   * @notice Get globalRoomIndex.
   */
  function getGlobalRoomIndex() internal view returns (uint256 globalRoomIndex) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get globalRoomIndex.
   */
  function _getGlobalRoomIndex() internal view returns (uint256 globalRoomIndex) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set globalRoomIndex.
   */
  function setGlobalRoomIndex(uint256 globalRoomIndex) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((globalRoomIndex)), _fieldLayout);
  }

  /**
   * @notice Set globalRoomIndex.
   */
  function _setGlobalRoomIndex(uint256 globalRoomIndex) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((globalRoomIndex)), _fieldLayout);
  }

  /**
   * @notice Get globalRatIndex.
   */
  function getGlobalRatIndex() internal view returns (uint256 globalRatIndex) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get globalRatIndex.
   */
  function _getGlobalRatIndex() internal view returns (uint256 globalRatIndex) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set globalRatIndex.
   */
  function setGlobalRatIndex(uint256 globalRatIndex) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((globalRatIndex)), _fieldLayout);
  }

  /**
   * @notice Set globalRatIndex.
   */
  function _setGlobalRatIndex(uint256 globalRatIndex) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((globalRatIndex)), _fieldLayout);
  }

  /**
   * @notice Get ratCreationCost.
   */
  function getRatCreationCost() internal view returns (uint256 ratCreationCost) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get ratCreationCost.
   */
  function _getRatCreationCost() internal view returns (uint256 ratCreationCost) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set ratCreationCost.
   */
  function setRatCreationCost(uint256 ratCreationCost) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((ratCreationCost)), _fieldLayout);
  }

  /**
   * @notice Set ratCreationCost.
   */
  function _setRatCreationCost(uint256 ratCreationCost) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((ratCreationCost)), _fieldLayout);
  }

  /**
   * @notice Get roomCreationCost.
   */
  function getRoomCreationCost() internal view returns (uint256 roomCreationCost) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 5, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get roomCreationCost.
   */
  function _getRoomCreationCost() internal view returns (uint256 roomCreationCost) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 5, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set roomCreationCost.
   */
  function setRoomCreationCost(uint256 roomCreationCost) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked((roomCreationCost)), _fieldLayout);
  }

  /**
   * @notice Set roomCreationCost.
   */
  function _setRoomCreationCost(uint256 roomCreationCost) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked((roomCreationCost)), _fieldLayout);
  }

  /**
   * @notice Get maxInventorySize.
   */
  function getMaxInventorySize() internal view returns (uint32 maxInventorySize) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 6, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get maxInventorySize.
   */
  function _getMaxInventorySize() internal view returns (uint32 maxInventorySize) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 6, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set maxInventorySize.
   */
  function setMaxInventorySize(uint32 maxInventorySize) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 6, abi.encodePacked((maxInventorySize)), _fieldLayout);
  }

  /**
   * @notice Set maxInventorySize.
   */
  function _setMaxInventorySize(uint32 maxInventorySize) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 6, abi.encodePacked((maxInventorySize)), _fieldLayout);
  }

  /**
   * @notice Get maxTraitsSize.
   */
  function getMaxTraitsSize() internal view returns (uint32 maxTraitsSize) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 7, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get maxTraitsSize.
   */
  function _getMaxTraitsSize() internal view returns (uint32 maxTraitsSize) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 7, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set maxTraitsSize.
   */
  function setMaxTraitsSize(uint32 maxTraitsSize) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 7, abi.encodePacked((maxTraitsSize)), _fieldLayout);
  }

  /**
   * @notice Set maxTraitsSize.
   */
  function _setMaxTraitsSize(uint32 maxTraitsSize) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 7, abi.encodePacked((maxTraitsSize)), _fieldLayout);
  }

  /**
   * @notice Get minRoomPromptLength.
   */
  function getMinRoomPromptLength() internal view returns (uint32 minRoomPromptLength) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 8, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get minRoomPromptLength.
   */
  function _getMinRoomPromptLength() internal view returns (uint32 minRoomPromptLength) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 8, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set minRoomPromptLength.
   */
  function setMinRoomPromptLength(uint32 minRoomPromptLength) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 8, abi.encodePacked((minRoomPromptLength)), _fieldLayout);
  }

  /**
   * @notice Set minRoomPromptLength.
   */
  function _setMinRoomPromptLength(uint32 minRoomPromptLength) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 8, abi.encodePacked((minRoomPromptLength)), _fieldLayout);
  }

  /**
   * @notice Get maxRoomPromptLength.
   */
  function getMaxRoomPromptLength() internal view returns (uint32 maxRoomPromptLength) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 9, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get maxRoomPromptLength.
   */
  function _getMaxRoomPromptLength() internal view returns (uint32 maxRoomPromptLength) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 9, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set maxRoomPromptLength.
   */
  function setMaxRoomPromptLength(uint32 maxRoomPromptLength) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 9, abi.encodePacked((maxRoomPromptLength)), _fieldLayout);
  }

  /**
   * @notice Set maxRoomPromptLength.
   */
  function _setMaxRoomPromptLength(uint32 maxRoomPromptLength) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 9, abi.encodePacked((maxRoomPromptLength)), _fieldLayout);
  }

  /**
   * @notice Get cooldownCloseRoom.
   */
  function getCooldownCloseRoom() internal view returns (uint32 cooldownCloseRoom) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 10, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get cooldownCloseRoom.
   */
  function _getCooldownCloseRoom() internal view returns (uint32 cooldownCloseRoom) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 10, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set cooldownCloseRoom.
   */
  function setCooldownCloseRoom(uint32 cooldownCloseRoom) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 10, abi.encodePacked((cooldownCloseRoom)), _fieldLayout);
  }

  /**
   * @notice Set cooldownCloseRoom.
   */
  function _setCooldownCloseRoom(uint32 cooldownCloseRoom) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 10, abi.encodePacked((cooldownCloseRoom)), _fieldLayout);
  }

  /**
   * @notice Get cooldownReenterRoom.
   */
  function getCooldownReenterRoom() internal view returns (uint32 cooldownReenterRoom) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 11, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get cooldownReenterRoom.
   */
  function _getCooldownReenterRoom() internal view returns (uint32 cooldownReenterRoom) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 11, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set cooldownReenterRoom.
   */
  function setCooldownReenterRoom(uint32 cooldownReenterRoom) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 11, abi.encodePacked((cooldownReenterRoom)), _fieldLayout);
  }

  /**
   * @notice Set cooldownReenterRoom.
   */
  function _setCooldownReenterRoom(uint32 cooldownReenterRoom) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 11, abi.encodePacked((cooldownReenterRoom)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get() internal view returns (GameConfigData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get() internal view returns (GameConfigData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    address adminAddress,
    bytes32 adminId,
    uint256 globalRoomIndex,
    uint256 globalRatIndex,
    uint256 ratCreationCost,
    uint256 roomCreationCost,
    uint32 maxInventorySize,
    uint32 maxTraitsSize,
    uint32 minRoomPromptLength,
    uint32 maxRoomPromptLength,
    uint32 cooldownCloseRoom,
    uint32 cooldownReenterRoom
  ) internal {
    bytes memory _staticData = encodeStatic(
      adminAddress,
      adminId,
      globalRoomIndex,
      globalRatIndex,
      ratCreationCost,
      roomCreationCost,
      maxInventorySize,
      maxTraitsSize,
      minRoomPromptLength,
      maxRoomPromptLength,
      cooldownCloseRoom,
      cooldownReenterRoom
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    address adminAddress,
    bytes32 adminId,
    uint256 globalRoomIndex,
    uint256 globalRatIndex,
    uint256 ratCreationCost,
    uint256 roomCreationCost,
    uint32 maxInventorySize,
    uint32 maxTraitsSize,
    uint32 minRoomPromptLength,
    uint32 maxRoomPromptLength,
    uint32 cooldownCloseRoom,
    uint32 cooldownReenterRoom
  ) internal {
    bytes memory _staticData = encodeStatic(
      adminAddress,
      adminId,
      globalRoomIndex,
      globalRatIndex,
      ratCreationCost,
      roomCreationCost,
      maxInventorySize,
      maxTraitsSize,
      minRoomPromptLength,
      maxRoomPromptLength,
      cooldownCloseRoom,
      cooldownReenterRoom
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(GameConfigData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.adminAddress,
      _table.adminId,
      _table.globalRoomIndex,
      _table.globalRatIndex,
      _table.ratCreationCost,
      _table.roomCreationCost,
      _table.maxInventorySize,
      _table.maxTraitsSize,
      _table.minRoomPromptLength,
      _table.maxRoomPromptLength,
      _table.cooldownCloseRoom,
      _table.cooldownReenterRoom
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(GameConfigData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.adminAddress,
      _table.adminId,
      _table.globalRoomIndex,
      _table.globalRatIndex,
      _table.ratCreationCost,
      _table.roomCreationCost,
      _table.maxInventorySize,
      _table.maxTraitsSize,
      _table.minRoomPromptLength,
      _table.maxRoomPromptLength,
      _table.cooldownCloseRoom,
      _table.cooldownReenterRoom
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  )
    internal
    pure
    returns (
      address adminAddress,
      bytes32 adminId,
      uint256 globalRoomIndex,
      uint256 globalRatIndex,
      uint256 ratCreationCost,
      uint256 roomCreationCost,
      uint32 maxInventorySize,
      uint32 maxTraitsSize,
      uint32 minRoomPromptLength,
      uint32 maxRoomPromptLength,
      uint32 cooldownCloseRoom,
      uint32 cooldownReenterRoom
    )
  {
    adminAddress = (address(Bytes.getBytes20(_blob, 0)));

    adminId = (Bytes.getBytes32(_blob, 20));

    globalRoomIndex = (uint256(Bytes.getBytes32(_blob, 52)));

    globalRatIndex = (uint256(Bytes.getBytes32(_blob, 84)));

    ratCreationCost = (uint256(Bytes.getBytes32(_blob, 116)));

    roomCreationCost = (uint256(Bytes.getBytes32(_blob, 148)));

    maxInventorySize = (uint32(Bytes.getBytes4(_blob, 180)));

    maxTraitsSize = (uint32(Bytes.getBytes4(_blob, 184)));

    minRoomPromptLength = (uint32(Bytes.getBytes4(_blob, 188)));

    maxRoomPromptLength = (uint32(Bytes.getBytes4(_blob, 192)));

    cooldownCloseRoom = (uint32(Bytes.getBytes4(_blob, 196)));

    cooldownReenterRoom = (uint32(Bytes.getBytes4(_blob, 200)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (GameConfigData memory _table) {
    (
      _table.adminAddress,
      _table.adminId,
      _table.globalRoomIndex,
      _table.globalRatIndex,
      _table.ratCreationCost,
      _table.roomCreationCost,
      _table.maxInventorySize,
      _table.maxTraitsSize,
      _table.minRoomPromptLength,
      _table.maxRoomPromptLength,
      _table.cooldownCloseRoom,
      _table.cooldownReenterRoom
    ) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord() internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord() internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    address adminAddress,
    bytes32 adminId,
    uint256 globalRoomIndex,
    uint256 globalRatIndex,
    uint256 ratCreationCost,
    uint256 roomCreationCost,
    uint32 maxInventorySize,
    uint32 maxTraitsSize,
    uint32 minRoomPromptLength,
    uint32 maxRoomPromptLength,
    uint32 cooldownCloseRoom,
    uint32 cooldownReenterRoom
  ) internal pure returns (bytes memory) {
    return
      abi.encodePacked(
        adminAddress,
        adminId,
        globalRoomIndex,
        globalRatIndex,
        ratCreationCost,
        roomCreationCost,
        maxInventorySize,
        maxTraitsSize,
        minRoomPromptLength,
        maxRoomPromptLength,
        cooldownCloseRoom,
        cooldownReenterRoom
      );
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    address adminAddress,
    bytes32 adminId,
    uint256 globalRoomIndex,
    uint256 globalRatIndex,
    uint256 ratCreationCost,
    uint256 roomCreationCost,
    uint32 maxInventorySize,
    uint32 maxTraitsSize,
    uint32 minRoomPromptLength,
    uint32 maxRoomPromptLength,
    uint32 cooldownCloseRoom,
    uint32 cooldownReenterRoom
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(
      adminAddress,
      adminId,
      globalRoomIndex,
      globalRatIndex,
      ratCreationCost,
      roomCreationCost,
      maxInventorySize,
      maxTraitsSize,
      minRoomPromptLength,
      maxRoomPromptLength,
      cooldownCloseRoom,
      cooldownReenterRoom
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple() internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    return _keyTuple;
  }
}
