// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct GamePercentagesConfigData {
  uint32 maxValuePerWin;
  uint32 minRatValueToEnter;
  uint32 taxationLiquidateRat;
  uint32 taxationCloseRoom;
}

library GamePercentagesConfig {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "ratfun", name: "GamePercentagesC", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x746272617466756e000000000000000047616d6550657263656e746167657343);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0010040004040404000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of ()
  Schema constant _keySchema = Schema.wrap(0x0000000000000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint32, uint32, uint32, uint32)
  Schema constant _valueSchema = Schema.wrap(0x0010040003030303000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](0);
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](4);
    fieldNames[0] = "maxValuePerWin";
    fieldNames[1] = "minRatValueToEnter";
    fieldNames[2] = "taxationLiquidateRat";
    fieldNames[3] = "taxationCloseRoom";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get maxValuePerWin.
   */
  function getMaxValuePerWin() internal view returns (uint32 maxValuePerWin) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get maxValuePerWin.
   */
  function _getMaxValuePerWin() internal view returns (uint32 maxValuePerWin) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set maxValuePerWin.
   */
  function setMaxValuePerWin(uint32 maxValuePerWin) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((maxValuePerWin)), _fieldLayout);
  }

  /**
   * @notice Set maxValuePerWin.
   */
  function _setMaxValuePerWin(uint32 maxValuePerWin) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((maxValuePerWin)), _fieldLayout);
  }

  /**
   * @notice Get minRatValueToEnter.
   */
  function getMinRatValueToEnter() internal view returns (uint32 minRatValueToEnter) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get minRatValueToEnter.
   */
  function _getMinRatValueToEnter() internal view returns (uint32 minRatValueToEnter) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set minRatValueToEnter.
   */
  function setMinRatValueToEnter(uint32 minRatValueToEnter) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((minRatValueToEnter)), _fieldLayout);
  }

  /**
   * @notice Set minRatValueToEnter.
   */
  function _setMinRatValueToEnter(uint32 minRatValueToEnter) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((minRatValueToEnter)), _fieldLayout);
  }

  /**
   * @notice Get taxationLiquidateRat.
   */
  function getTaxationLiquidateRat() internal view returns (uint32 taxationLiquidateRat) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get taxationLiquidateRat.
   */
  function _getTaxationLiquidateRat() internal view returns (uint32 taxationLiquidateRat) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set taxationLiquidateRat.
   */
  function setTaxationLiquidateRat(uint32 taxationLiquidateRat) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((taxationLiquidateRat)), _fieldLayout);
  }

  /**
   * @notice Set taxationLiquidateRat.
   */
  function _setTaxationLiquidateRat(uint32 taxationLiquidateRat) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((taxationLiquidateRat)), _fieldLayout);
  }

  /**
   * @notice Get taxationCloseRoom.
   */
  function getTaxationCloseRoom() internal view returns (uint32 taxationCloseRoom) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get taxationCloseRoom.
   */
  function _getTaxationCloseRoom() internal view returns (uint32 taxationCloseRoom) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set taxationCloseRoom.
   */
  function setTaxationCloseRoom(uint32 taxationCloseRoom) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((taxationCloseRoom)), _fieldLayout);
  }

  /**
   * @notice Set taxationCloseRoom.
   */
  function _setTaxationCloseRoom(uint32 taxationCloseRoom) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((taxationCloseRoom)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get() internal view returns (GamePercentagesConfigData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get() internal view returns (GamePercentagesConfigData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    uint32 maxValuePerWin,
    uint32 minRatValueToEnter,
    uint32 taxationLiquidateRat,
    uint32 taxationCloseRoom
  ) internal {
    bytes memory _staticData = encodeStatic(
      maxValuePerWin,
      minRatValueToEnter,
      taxationLiquidateRat,
      taxationCloseRoom
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    uint32 maxValuePerWin,
    uint32 minRatValueToEnter,
    uint32 taxationLiquidateRat,
    uint32 taxationCloseRoom
  ) internal {
    bytes memory _staticData = encodeStatic(
      maxValuePerWin,
      minRatValueToEnter,
      taxationLiquidateRat,
      taxationCloseRoom
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(GamePercentagesConfigData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.maxValuePerWin,
      _table.minRatValueToEnter,
      _table.taxationLiquidateRat,
      _table.taxationCloseRoom
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(GamePercentagesConfigData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.maxValuePerWin,
      _table.minRatValueToEnter,
      _table.taxationLiquidateRat,
      _table.taxationCloseRoom
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  )
    internal
    pure
    returns (uint32 maxValuePerWin, uint32 minRatValueToEnter, uint32 taxationLiquidateRat, uint32 taxationCloseRoom)
  {
    maxValuePerWin = (uint32(Bytes.getBytes4(_blob, 0)));

    minRatValueToEnter = (uint32(Bytes.getBytes4(_blob, 4)));

    taxationLiquidateRat = (uint32(Bytes.getBytes4(_blob, 8)));

    taxationCloseRoom = (uint32(Bytes.getBytes4(_blob, 12)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (GamePercentagesConfigData memory _table) {
    (
      _table.maxValuePerWin,
      _table.minRatValueToEnter,
      _table.taxationLiquidateRat,
      _table.taxationCloseRoom
    ) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord() internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord() internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    uint32 maxValuePerWin,
    uint32 minRatValueToEnter,
    uint32 taxationLiquidateRat,
    uint32 taxationCloseRoom
  ) internal pure returns (bytes memory) {
    return abi.encodePacked(maxValuePerWin, minRatValueToEnter, taxationLiquidateRat, taxationCloseRoom);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    uint32 maxValuePerWin,
    uint32 minRatValueToEnter,
    uint32 taxationLiquidateRat,
    uint32 taxationCloseRoom
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(
      maxValuePerWin,
      minRatValueToEnter,
      taxationLiquidateRat,
      taxationCloseRoom
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple() internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    return _keyTuple;
  }
}
