// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct GameConfigData {
  address adminAddress;
  uint32 globalRoomIndex;
  uint32 globalRatIndex;
  uint32 roomCreationCost;
  uint32 maxRoomPromptLength;
  uint32 maxInventorySize;
  uint32 maxLoadOutSize;
  uint32 maxTraitsSize;
}

library GameConfig {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "ratroom", name: "GameConfig", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x7462726174726f6f6d0000000000000047616d65436f6e666967000000000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0030080014040404040404040000000000000000000000000000000000000000);

  // Hex-encoded key schema of ()
  Schema constant _keySchema = Schema.wrap(0x0000000000000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (address, uint32, uint32, uint32, uint32, uint32, uint32, uint32)
  Schema constant _valueSchema = Schema.wrap(0x0030080061030303030303030000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](0);
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](8);
    fieldNames[0] = "adminAddress";
    fieldNames[1] = "globalRoomIndex";
    fieldNames[2] = "globalRatIndex";
    fieldNames[3] = "roomCreationCost";
    fieldNames[4] = "maxRoomPromptLength";
    fieldNames[5] = "maxInventorySize";
    fieldNames[6] = "maxLoadOutSize";
    fieldNames[7] = "maxTraitsSize";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get adminAddress.
   */
  function getAdminAddress() internal view returns (address adminAddress) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Get adminAddress.
   */
  function _getAdminAddress() internal view returns (address adminAddress) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Set adminAddress.
   */
  function setAdminAddress(address adminAddress) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((adminAddress)), _fieldLayout);
  }

  /**
   * @notice Set adminAddress.
   */
  function _setAdminAddress(address adminAddress) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((adminAddress)), _fieldLayout);
  }

  /**
   * @notice Get globalRoomIndex.
   */
  function getGlobalRoomIndex() internal view returns (uint32 globalRoomIndex) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get globalRoomIndex.
   */
  function _getGlobalRoomIndex() internal view returns (uint32 globalRoomIndex) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set globalRoomIndex.
   */
  function setGlobalRoomIndex(uint32 globalRoomIndex) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((globalRoomIndex)), _fieldLayout);
  }

  /**
   * @notice Set globalRoomIndex.
   */
  function _setGlobalRoomIndex(uint32 globalRoomIndex) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((globalRoomIndex)), _fieldLayout);
  }

  /**
   * @notice Get globalRatIndex.
   */
  function getGlobalRatIndex() internal view returns (uint32 globalRatIndex) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get globalRatIndex.
   */
  function _getGlobalRatIndex() internal view returns (uint32 globalRatIndex) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set globalRatIndex.
   */
  function setGlobalRatIndex(uint32 globalRatIndex) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((globalRatIndex)), _fieldLayout);
  }

  /**
   * @notice Set globalRatIndex.
   */
  function _setGlobalRatIndex(uint32 globalRatIndex) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((globalRatIndex)), _fieldLayout);
  }

  /**
   * @notice Get roomCreationCost.
   */
  function getRoomCreationCost() internal view returns (uint32 roomCreationCost) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get roomCreationCost.
   */
  function _getRoomCreationCost() internal view returns (uint32 roomCreationCost) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set roomCreationCost.
   */
  function setRoomCreationCost(uint32 roomCreationCost) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((roomCreationCost)), _fieldLayout);
  }

  /**
   * @notice Set roomCreationCost.
   */
  function _setRoomCreationCost(uint32 roomCreationCost) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((roomCreationCost)), _fieldLayout);
  }

  /**
   * @notice Get maxRoomPromptLength.
   */
  function getMaxRoomPromptLength() internal view returns (uint32 maxRoomPromptLength) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get maxRoomPromptLength.
   */
  function _getMaxRoomPromptLength() internal view returns (uint32 maxRoomPromptLength) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set maxRoomPromptLength.
   */
  function setMaxRoomPromptLength(uint32 maxRoomPromptLength) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((maxRoomPromptLength)), _fieldLayout);
  }

  /**
   * @notice Set maxRoomPromptLength.
   */
  function _setMaxRoomPromptLength(uint32 maxRoomPromptLength) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((maxRoomPromptLength)), _fieldLayout);
  }

  /**
   * @notice Get maxInventorySize.
   */
  function getMaxInventorySize() internal view returns (uint32 maxInventorySize) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 5, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get maxInventorySize.
   */
  function _getMaxInventorySize() internal view returns (uint32 maxInventorySize) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 5, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set maxInventorySize.
   */
  function setMaxInventorySize(uint32 maxInventorySize) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked((maxInventorySize)), _fieldLayout);
  }

  /**
   * @notice Set maxInventorySize.
   */
  function _setMaxInventorySize(uint32 maxInventorySize) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked((maxInventorySize)), _fieldLayout);
  }

  /**
   * @notice Get maxLoadOutSize.
   */
  function getMaxLoadOutSize() internal view returns (uint32 maxLoadOutSize) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 6, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get maxLoadOutSize.
   */
  function _getMaxLoadOutSize() internal view returns (uint32 maxLoadOutSize) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 6, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set maxLoadOutSize.
   */
  function setMaxLoadOutSize(uint32 maxLoadOutSize) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 6, abi.encodePacked((maxLoadOutSize)), _fieldLayout);
  }

  /**
   * @notice Set maxLoadOutSize.
   */
  function _setMaxLoadOutSize(uint32 maxLoadOutSize) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 6, abi.encodePacked((maxLoadOutSize)), _fieldLayout);
  }

  /**
   * @notice Get maxTraitsSize.
   */
  function getMaxTraitsSize() internal view returns (uint32 maxTraitsSize) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 7, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get maxTraitsSize.
   */
  function _getMaxTraitsSize() internal view returns (uint32 maxTraitsSize) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 7, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set maxTraitsSize.
   */
  function setMaxTraitsSize(uint32 maxTraitsSize) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 7, abi.encodePacked((maxTraitsSize)), _fieldLayout);
  }

  /**
   * @notice Set maxTraitsSize.
   */
  function _setMaxTraitsSize(uint32 maxTraitsSize) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 7, abi.encodePacked((maxTraitsSize)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get() internal view returns (GameConfigData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get() internal view returns (GameConfigData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    address adminAddress,
    uint32 globalRoomIndex,
    uint32 globalRatIndex,
    uint32 roomCreationCost,
    uint32 maxRoomPromptLength,
    uint32 maxInventorySize,
    uint32 maxLoadOutSize,
    uint32 maxTraitsSize
  ) internal {
    bytes memory _staticData = encodeStatic(
      adminAddress,
      globalRoomIndex,
      globalRatIndex,
      roomCreationCost,
      maxRoomPromptLength,
      maxInventorySize,
      maxLoadOutSize,
      maxTraitsSize
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    address adminAddress,
    uint32 globalRoomIndex,
    uint32 globalRatIndex,
    uint32 roomCreationCost,
    uint32 maxRoomPromptLength,
    uint32 maxInventorySize,
    uint32 maxLoadOutSize,
    uint32 maxTraitsSize
  ) internal {
    bytes memory _staticData = encodeStatic(
      adminAddress,
      globalRoomIndex,
      globalRatIndex,
      roomCreationCost,
      maxRoomPromptLength,
      maxInventorySize,
      maxLoadOutSize,
      maxTraitsSize
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(GameConfigData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.adminAddress,
      _table.globalRoomIndex,
      _table.globalRatIndex,
      _table.roomCreationCost,
      _table.maxRoomPromptLength,
      _table.maxInventorySize,
      _table.maxLoadOutSize,
      _table.maxTraitsSize
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(GameConfigData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.adminAddress,
      _table.globalRoomIndex,
      _table.globalRatIndex,
      _table.roomCreationCost,
      _table.maxRoomPromptLength,
      _table.maxInventorySize,
      _table.maxLoadOutSize,
      _table.maxTraitsSize
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  )
    internal
    pure
    returns (
      address adminAddress,
      uint32 globalRoomIndex,
      uint32 globalRatIndex,
      uint32 roomCreationCost,
      uint32 maxRoomPromptLength,
      uint32 maxInventorySize,
      uint32 maxLoadOutSize,
      uint32 maxTraitsSize
    )
  {
    adminAddress = (address(Bytes.getBytes20(_blob, 0)));

    globalRoomIndex = (uint32(Bytes.getBytes4(_blob, 20)));

    globalRatIndex = (uint32(Bytes.getBytes4(_blob, 24)));

    roomCreationCost = (uint32(Bytes.getBytes4(_blob, 28)));

    maxRoomPromptLength = (uint32(Bytes.getBytes4(_blob, 32)));

    maxInventorySize = (uint32(Bytes.getBytes4(_blob, 36)));

    maxLoadOutSize = (uint32(Bytes.getBytes4(_blob, 40)));

    maxTraitsSize = (uint32(Bytes.getBytes4(_blob, 44)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (GameConfigData memory _table) {
    (
      _table.adminAddress,
      _table.globalRoomIndex,
      _table.globalRatIndex,
      _table.roomCreationCost,
      _table.maxRoomPromptLength,
      _table.maxInventorySize,
      _table.maxLoadOutSize,
      _table.maxTraitsSize
    ) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord() internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord() internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    address adminAddress,
    uint32 globalRoomIndex,
    uint32 globalRatIndex,
    uint32 roomCreationCost,
    uint32 maxRoomPromptLength,
    uint32 maxInventorySize,
    uint32 maxLoadOutSize,
    uint32 maxTraitsSize
  ) internal pure returns (bytes memory) {
    return
      abi.encodePacked(
        adminAddress,
        globalRoomIndex,
        globalRatIndex,
        roomCreationCost,
        maxRoomPromptLength,
        maxInventorySize,
        maxLoadOutSize,
        maxTraitsSize
      );
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    address adminAddress,
    uint32 globalRoomIndex,
    uint32 globalRatIndex,
    uint32 roomCreationCost,
    uint32 maxRoomPromptLength,
    uint32 maxInventorySize,
    uint32 maxLoadOutSize,
    uint32 maxTraitsSize
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(
      adminAddress,
      globalRoomIndex,
      globalRatIndex,
      roomCreationCost,
      maxRoomPromptLength,
      maxInventorySize,
      maxLoadOutSize,
      maxTraitsSize
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple() internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    return _keyTuple;
  }
}
