// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct GameConfigData {
  address adminAddress;
  bytes32 adminId;
  uint256 ratCreationCost;
  uint256 roomCreationCost;
  uint32 maxInventorySize;
  uint32 maxRoomPromptLength;
  uint32 cooldownCloseRoom;
  uint32 taxationSellItem;
  uint32 taxationLiquidateRat;
  uint32 taxationCloseRoom;
}

library GameConfig {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "ratfun", name: "GameConfig", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x746272617466756e000000000000000047616d65436f6e666967000000000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x008c0a0014202020040404040404000000000000000000000000000000000000);

  // Hex-encoded key schema of ()
  Schema constant _keySchema = Schema.wrap(0x0000000000000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (address, bytes32, uint256, uint256, uint32, uint32, uint32, uint32, uint32, uint32)
  Schema constant _valueSchema = Schema.wrap(0x008c0a00615f1f1f030303030303000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](0);
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](10);
    fieldNames[0] = "adminAddress";
    fieldNames[1] = "adminId";
    fieldNames[2] = "ratCreationCost";
    fieldNames[3] = "roomCreationCost";
    fieldNames[4] = "maxInventorySize";
    fieldNames[5] = "maxRoomPromptLength";
    fieldNames[6] = "cooldownCloseRoom";
    fieldNames[7] = "taxationSellItem";
    fieldNames[8] = "taxationLiquidateRat";
    fieldNames[9] = "taxationCloseRoom";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get adminAddress.
   */
  function getAdminAddress() internal view returns (address adminAddress) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Get adminAddress.
   */
  function _getAdminAddress() internal view returns (address adminAddress) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Set adminAddress.
   */
  function setAdminAddress(address adminAddress) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((adminAddress)), _fieldLayout);
  }

  /**
   * @notice Set adminAddress.
   */
  function _setAdminAddress(address adminAddress) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((adminAddress)), _fieldLayout);
  }

  /**
   * @notice Get adminId.
   */
  function getAdminId() internal view returns (bytes32 adminId) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (bytes32(_blob));
  }

  /**
   * @notice Get adminId.
   */
  function _getAdminId() internal view returns (bytes32 adminId) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (bytes32(_blob));
  }

  /**
   * @notice Set adminId.
   */
  function setAdminId(bytes32 adminId) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((adminId)), _fieldLayout);
  }

  /**
   * @notice Set adminId.
   */
  function _setAdminId(bytes32 adminId) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((adminId)), _fieldLayout);
  }

  /**
   * @notice Get ratCreationCost.
   */
  function getRatCreationCost() internal view returns (uint256 ratCreationCost) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get ratCreationCost.
   */
  function _getRatCreationCost() internal view returns (uint256 ratCreationCost) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set ratCreationCost.
   */
  function setRatCreationCost(uint256 ratCreationCost) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((ratCreationCost)), _fieldLayout);
  }

  /**
   * @notice Set ratCreationCost.
   */
  function _setRatCreationCost(uint256 ratCreationCost) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((ratCreationCost)), _fieldLayout);
  }

  /**
   * @notice Get roomCreationCost.
   */
  function getRoomCreationCost() internal view returns (uint256 roomCreationCost) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get roomCreationCost.
   */
  function _getRoomCreationCost() internal view returns (uint256 roomCreationCost) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set roomCreationCost.
   */
  function setRoomCreationCost(uint256 roomCreationCost) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((roomCreationCost)), _fieldLayout);
  }

  /**
   * @notice Set roomCreationCost.
   */
  function _setRoomCreationCost(uint256 roomCreationCost) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((roomCreationCost)), _fieldLayout);
  }

  /**
   * @notice Get maxInventorySize.
   */
  function getMaxInventorySize() internal view returns (uint32 maxInventorySize) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get maxInventorySize.
   */
  function _getMaxInventorySize() internal view returns (uint32 maxInventorySize) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set maxInventorySize.
   */
  function setMaxInventorySize(uint32 maxInventorySize) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((maxInventorySize)), _fieldLayout);
  }

  /**
   * @notice Set maxInventorySize.
   */
  function _setMaxInventorySize(uint32 maxInventorySize) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((maxInventorySize)), _fieldLayout);
  }

  /**
   * @notice Get maxRoomPromptLength.
   */
  function getMaxRoomPromptLength() internal view returns (uint32 maxRoomPromptLength) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 5, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get maxRoomPromptLength.
   */
  function _getMaxRoomPromptLength() internal view returns (uint32 maxRoomPromptLength) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 5, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set maxRoomPromptLength.
   */
  function setMaxRoomPromptLength(uint32 maxRoomPromptLength) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked((maxRoomPromptLength)), _fieldLayout);
  }

  /**
   * @notice Set maxRoomPromptLength.
   */
  function _setMaxRoomPromptLength(uint32 maxRoomPromptLength) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked((maxRoomPromptLength)), _fieldLayout);
  }

  /**
   * @notice Get cooldownCloseRoom.
   */
  function getCooldownCloseRoom() internal view returns (uint32 cooldownCloseRoom) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 6, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get cooldownCloseRoom.
   */
  function _getCooldownCloseRoom() internal view returns (uint32 cooldownCloseRoom) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 6, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set cooldownCloseRoom.
   */
  function setCooldownCloseRoom(uint32 cooldownCloseRoom) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 6, abi.encodePacked((cooldownCloseRoom)), _fieldLayout);
  }

  /**
   * @notice Set cooldownCloseRoom.
   */
  function _setCooldownCloseRoom(uint32 cooldownCloseRoom) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 6, abi.encodePacked((cooldownCloseRoom)), _fieldLayout);
  }

  /**
   * @notice Get taxationSellItem.
   */
  function getTaxationSellItem() internal view returns (uint32 taxationSellItem) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 7, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get taxationSellItem.
   */
  function _getTaxationSellItem() internal view returns (uint32 taxationSellItem) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 7, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set taxationSellItem.
   */
  function setTaxationSellItem(uint32 taxationSellItem) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 7, abi.encodePacked((taxationSellItem)), _fieldLayout);
  }

  /**
   * @notice Set taxationSellItem.
   */
  function _setTaxationSellItem(uint32 taxationSellItem) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 7, abi.encodePacked((taxationSellItem)), _fieldLayout);
  }

  /**
   * @notice Get taxationLiquidateRat.
   */
  function getTaxationLiquidateRat() internal view returns (uint32 taxationLiquidateRat) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 8, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get taxationLiquidateRat.
   */
  function _getTaxationLiquidateRat() internal view returns (uint32 taxationLiquidateRat) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 8, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set taxationLiquidateRat.
   */
  function setTaxationLiquidateRat(uint32 taxationLiquidateRat) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 8, abi.encodePacked((taxationLiquidateRat)), _fieldLayout);
  }

  /**
   * @notice Set taxationLiquidateRat.
   */
  function _setTaxationLiquidateRat(uint32 taxationLiquidateRat) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 8, abi.encodePacked((taxationLiquidateRat)), _fieldLayout);
  }

  /**
   * @notice Get taxationCloseRoom.
   */
  function getTaxationCloseRoom() internal view returns (uint32 taxationCloseRoom) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 9, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get taxationCloseRoom.
   */
  function _getTaxationCloseRoom() internal view returns (uint32 taxationCloseRoom) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 9, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set taxationCloseRoom.
   */
  function setTaxationCloseRoom(uint32 taxationCloseRoom) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 9, abi.encodePacked((taxationCloseRoom)), _fieldLayout);
  }

  /**
   * @notice Set taxationCloseRoom.
   */
  function _setTaxationCloseRoom(uint32 taxationCloseRoom) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 9, abi.encodePacked((taxationCloseRoom)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get() internal view returns (GameConfigData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get() internal view returns (GameConfigData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    address adminAddress,
    bytes32 adminId,
    uint256 ratCreationCost,
    uint256 roomCreationCost,
    uint32 maxInventorySize,
    uint32 maxRoomPromptLength,
    uint32 cooldownCloseRoom,
    uint32 taxationSellItem,
    uint32 taxationLiquidateRat,
    uint32 taxationCloseRoom
  ) internal {
    bytes memory _staticData = encodeStatic(
      adminAddress,
      adminId,
      ratCreationCost,
      roomCreationCost,
      maxInventorySize,
      maxRoomPromptLength,
      cooldownCloseRoom,
      taxationSellItem,
      taxationLiquidateRat,
      taxationCloseRoom
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    address adminAddress,
    bytes32 adminId,
    uint256 ratCreationCost,
    uint256 roomCreationCost,
    uint32 maxInventorySize,
    uint32 maxRoomPromptLength,
    uint32 cooldownCloseRoom,
    uint32 taxationSellItem,
    uint32 taxationLiquidateRat,
    uint32 taxationCloseRoom
  ) internal {
    bytes memory _staticData = encodeStatic(
      adminAddress,
      adminId,
      ratCreationCost,
      roomCreationCost,
      maxInventorySize,
      maxRoomPromptLength,
      cooldownCloseRoom,
      taxationSellItem,
      taxationLiquidateRat,
      taxationCloseRoom
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(GameConfigData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.adminAddress,
      _table.adminId,
      _table.ratCreationCost,
      _table.roomCreationCost,
      _table.maxInventorySize,
      _table.maxRoomPromptLength,
      _table.cooldownCloseRoom,
      _table.taxationSellItem,
      _table.taxationLiquidateRat,
      _table.taxationCloseRoom
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(GameConfigData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.adminAddress,
      _table.adminId,
      _table.ratCreationCost,
      _table.roomCreationCost,
      _table.maxInventorySize,
      _table.maxRoomPromptLength,
      _table.cooldownCloseRoom,
      _table.taxationSellItem,
      _table.taxationLiquidateRat,
      _table.taxationCloseRoom
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  )
    internal
    pure
    returns (
      address adminAddress,
      bytes32 adminId,
      uint256 ratCreationCost,
      uint256 roomCreationCost,
      uint32 maxInventorySize,
      uint32 maxRoomPromptLength,
      uint32 cooldownCloseRoom,
      uint32 taxationSellItem,
      uint32 taxationLiquidateRat,
      uint32 taxationCloseRoom
    )
  {
    adminAddress = (address(Bytes.getBytes20(_blob, 0)));

    adminId = (Bytes.getBytes32(_blob, 20));

    ratCreationCost = (uint256(Bytes.getBytes32(_blob, 52)));

    roomCreationCost = (uint256(Bytes.getBytes32(_blob, 84)));

    maxInventorySize = (uint32(Bytes.getBytes4(_blob, 116)));

    maxRoomPromptLength = (uint32(Bytes.getBytes4(_blob, 120)));

    cooldownCloseRoom = (uint32(Bytes.getBytes4(_blob, 124)));

    taxationSellItem = (uint32(Bytes.getBytes4(_blob, 128)));

    taxationLiquidateRat = (uint32(Bytes.getBytes4(_blob, 132)));

    taxationCloseRoom = (uint32(Bytes.getBytes4(_blob, 136)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (GameConfigData memory _table) {
    (
      _table.adminAddress,
      _table.adminId,
      _table.ratCreationCost,
      _table.roomCreationCost,
      _table.maxInventorySize,
      _table.maxRoomPromptLength,
      _table.cooldownCloseRoom,
      _table.taxationSellItem,
      _table.taxationLiquidateRat,
      _table.taxationCloseRoom
    ) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord() internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord() internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    address adminAddress,
    bytes32 adminId,
    uint256 ratCreationCost,
    uint256 roomCreationCost,
    uint32 maxInventorySize,
    uint32 maxRoomPromptLength,
    uint32 cooldownCloseRoom,
    uint32 taxationSellItem,
    uint32 taxationLiquidateRat,
    uint32 taxationCloseRoom
  ) internal pure returns (bytes memory) {
    return
      abi.encodePacked(
        adminAddress,
        adminId,
        ratCreationCost,
        roomCreationCost,
        maxInventorySize,
        maxRoomPromptLength,
        cooldownCloseRoom,
        taxationSellItem,
        taxationLiquidateRat,
        taxationCloseRoom
      );
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    address adminAddress,
    bytes32 adminId,
    uint256 ratCreationCost,
    uint256 roomCreationCost,
    uint32 maxInventorySize,
    uint32 maxRoomPromptLength,
    uint32 cooldownCloseRoom,
    uint32 taxationSellItem,
    uint32 taxationLiquidateRat,
    uint32 taxationCloseRoom
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(
      adminAddress,
      adminId,
      ratCreationCost,
      roomCreationCost,
      maxInventorySize,
      maxRoomPromptLength,
      cooldownCloseRoom,
      taxationSellItem,
      taxationLiquidateRat,
      taxationCloseRoom
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple() internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    return _keyTuple;
  }
}
