// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct WorldStatsData {
  uint256 globalRoomIndex;
  uint256 globalRatIndex;
  uint256 globalRatKillCount;
  uint256 lastKilledRatBlock;
}

library WorldStats {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "ratfun", name: "WorldStats", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x746272617466756e0000000000000000576f726c645374617473000000000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0080040020202020000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of ()
  Schema constant _keySchema = Schema.wrap(0x0000000000000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint256, uint256, uint256, uint256)
  Schema constant _valueSchema = Schema.wrap(0x008004001f1f1f1f000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](0);
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](4);
    fieldNames[0] = "globalRoomIndex";
    fieldNames[1] = "globalRatIndex";
    fieldNames[2] = "globalRatKillCount";
    fieldNames[3] = "lastKilledRatBlock";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get globalRoomIndex.
   */
  function getGlobalRoomIndex() internal view returns (uint256 globalRoomIndex) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get globalRoomIndex.
   */
  function _getGlobalRoomIndex() internal view returns (uint256 globalRoomIndex) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set globalRoomIndex.
   */
  function setGlobalRoomIndex(uint256 globalRoomIndex) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((globalRoomIndex)), _fieldLayout);
  }

  /**
   * @notice Set globalRoomIndex.
   */
  function _setGlobalRoomIndex(uint256 globalRoomIndex) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((globalRoomIndex)), _fieldLayout);
  }

  /**
   * @notice Get globalRatIndex.
   */
  function getGlobalRatIndex() internal view returns (uint256 globalRatIndex) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get globalRatIndex.
   */
  function _getGlobalRatIndex() internal view returns (uint256 globalRatIndex) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set globalRatIndex.
   */
  function setGlobalRatIndex(uint256 globalRatIndex) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((globalRatIndex)), _fieldLayout);
  }

  /**
   * @notice Set globalRatIndex.
   */
  function _setGlobalRatIndex(uint256 globalRatIndex) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((globalRatIndex)), _fieldLayout);
  }

  /**
   * @notice Get globalRatKillCount.
   */
  function getGlobalRatKillCount() internal view returns (uint256 globalRatKillCount) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get globalRatKillCount.
   */
  function _getGlobalRatKillCount() internal view returns (uint256 globalRatKillCount) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set globalRatKillCount.
   */
  function setGlobalRatKillCount(uint256 globalRatKillCount) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((globalRatKillCount)), _fieldLayout);
  }

  /**
   * @notice Set globalRatKillCount.
   */
  function _setGlobalRatKillCount(uint256 globalRatKillCount) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((globalRatKillCount)), _fieldLayout);
  }

  /**
   * @notice Get lastKilledRatBlock.
   */
  function getLastKilledRatBlock() internal view returns (uint256 lastKilledRatBlock) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get lastKilledRatBlock.
   */
  function _getLastKilledRatBlock() internal view returns (uint256 lastKilledRatBlock) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set lastKilledRatBlock.
   */
  function setLastKilledRatBlock(uint256 lastKilledRatBlock) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((lastKilledRatBlock)), _fieldLayout);
  }

  /**
   * @notice Set lastKilledRatBlock.
   */
  function _setLastKilledRatBlock(uint256 lastKilledRatBlock) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((lastKilledRatBlock)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get() internal view returns (WorldStatsData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get() internal view returns (WorldStatsData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    uint256 globalRoomIndex,
    uint256 globalRatIndex,
    uint256 globalRatKillCount,
    uint256 lastKilledRatBlock
  ) internal {
    bytes memory _staticData = encodeStatic(globalRoomIndex, globalRatIndex, globalRatKillCount, lastKilledRatBlock);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    uint256 globalRoomIndex,
    uint256 globalRatIndex,
    uint256 globalRatKillCount,
    uint256 lastKilledRatBlock
  ) internal {
    bytes memory _staticData = encodeStatic(globalRoomIndex, globalRatIndex, globalRatKillCount, lastKilledRatBlock);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(WorldStatsData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.globalRoomIndex,
      _table.globalRatIndex,
      _table.globalRatKillCount,
      _table.lastKilledRatBlock
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(WorldStatsData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.globalRoomIndex,
      _table.globalRatIndex,
      _table.globalRatKillCount,
      _table.lastKilledRatBlock
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  )
    internal
    pure
    returns (uint256 globalRoomIndex, uint256 globalRatIndex, uint256 globalRatKillCount, uint256 lastKilledRatBlock)
  {
    globalRoomIndex = (uint256(Bytes.getBytes32(_blob, 0)));

    globalRatIndex = (uint256(Bytes.getBytes32(_blob, 32)));

    globalRatKillCount = (uint256(Bytes.getBytes32(_blob, 64)));

    lastKilledRatBlock = (uint256(Bytes.getBytes32(_blob, 96)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (WorldStatsData memory _table) {
    (
      _table.globalRoomIndex,
      _table.globalRatIndex,
      _table.globalRatKillCount,
      _table.lastKilledRatBlock
    ) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord() internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord() internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    uint256 globalRoomIndex,
    uint256 globalRatIndex,
    uint256 globalRatKillCount,
    uint256 lastKilledRatBlock
  ) internal pure returns (bytes memory) {
    return abi.encodePacked(globalRoomIndex, globalRatIndex, globalRatKillCount, lastKilledRatBlock);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    uint256 globalRoomIndex,
    uint256 globalRatIndex,
    uint256 globalRatKillCount,
    uint256 lastKilledRatBlock
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(globalRoomIndex, globalRatIndex, globalRatKillCount, lastKilledRatBlock);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple() internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    return _keyTuple;
  }
}
