import { CURRENCY_SYMBOL } from "$lib/modules/ui/constants"

const stringsData = {
  "en-US": {
    address: "Address",
    admin: "Cashboard",
    action: "Action",
    all: "All",
    activeProfit: "Active profit",
    adminUnlocked: "Admin unlocked",
    adminUnlockedMessage: "You unlocked the cashboard",
    ago: "ago",
    alive: "Alive",
    active: "Active",
    activeTrips: "Active trips",
    allowance: "Allowance",
    approveAllowance: "Approve max allowance",
    approveAllowanceInstruction: "Allow the contract to spend on your behalf",
    approvingAllowance: "Approving allowance",
    authorFullTitle: "Moving Castles GmbH",
    back: "Back",
    balance: "Balance",
    blockNumber: "BlockNumber",
    bottomMarqueeText: "THERE ARE NOT BAD TRIPS, ONLY BAD RATS.",
    buyRat: "Buy Rat",
    buySomeTokens: `Buy some slopamine (${CURRENCY_SYMBOL})`,
    buyTokens: (amount: number): string =>
      `Buy ${amount} Slopamine ({CURRENCY_SYMBOL}) for 0.001ETH`,
    cancel: "Abort",
    causeOfDeathShort: "CoD",
    confirm: "Confirm",
    confirmLiquidationMessage: (name: string): string =>
      `Are you sure you want to liquidate ${name}?`,
    comeDown: "COME DOWN",
    connectBurner: "Connect Burner",
    connectWallet: "Connect wallet",
    connectedWallet: "Connected wallet",
    confirmLiquidateTripPrompt: (index: number): string =>
      `Are you sure you want to liquidate trip #${index}?`,
    cost: "Cost:",
    createdTrip: "created trip",
    creatingTripIn: "Creating trip in:",
    creationBlock: "Create @",
    creationCost: "Creation Cost",
    createTrip: "Create Trip",
    createTripButton: "Create trip",
    createTripPlaceholder: "You're creating a trip...",
    creator: "Creator",
    currentRat: "Current Rat",
    debug: "Debug",
    deployed: "deployed",
    destroyedTrip: "destroyed trip",
    died: "DIED",
    dieFromTrip: "die from trip #",
    dieInTrip: "die in trip",
    diedTripping: "died tripping #",
    disconnectWallet: "Disconnect wallet",
    empty: "Empty",
    enjoySkillfully: "ENJOY SKILLFULLY",
    events: "Events",
    environment: "Environment",
    erc20Balance: "ERC20 Balance",
    filter: "Filter",
    fomoAlertBalance: (balance: number): string => `FOMO ALERT! Balance is ${balance}`,
    forceRatLiquidation: "Force liquidate rat",
    getFreeTokens: (amount: number): string => `Get ${amount} free slopamine (${CURRENCY_SYMBOL})`,
    gettingRat: "Getting your rat...",
    gettingTokens: "Getting tokens",
    getTokens: (amount: number): string => `Get ${amount} $RAT`,
    graph: "Graph",
    hasTokens: "Has tokens",
    health: "HEALTH",
    home: "Home",
    hot: "HOT",
    insufficientBalance: "Insufficient balance",
    inventory: "Inventory",
    issuingMemberCard: "Issuing member card",
    killInProgress: "KILLING IN PROGRESS",
    kills: "Kills",
    lastVisit: "Last Visit",
    lastVisitedSecondsAgo: (seconds: number): string => `Last visited ${seconds} seconds ago`,
    let: "let",
    liquidate: "Liquidate",
    liquidated: "liquidated",
    liquidatingTrip: "Liquidating trip",
    log: "Log",
    liquidateRatButtonText: "Liquidate Rat",
    liquidateRatInstruction: "Liquidate rat to get the value added to your wallet",
    liquidationBlockShort: "Liq. @",
    liquidationValueShort: "Liq. Val.",
    loadingMsg: "LoadingMsg",
    loadingPercentage: "Loading%",
    locked: "locked",
    masterKey: "Cashboard unlocked",
    maxReward: "Max reward",
    maxValuePerWin: "Max value per win",
    maxValuePerWinLabel: "MAX VALUE PER WIN",
    messageCannotBeEmpty: "Message cannot be empty",
    minRatValueToEnter: "Min rat value to enter",
    minRatValueToTrip: "MIN RAT VALUE TO TRIP",
    minRatValueWarning: (value: number): string => `Rat value too low (at least ${value})`,
    moveOn: "MOVE ON",
    name: "Name",
    nameCannotBeEmpty: "Name cannot be empty",
    nameTooLong: "Name is too long (maximum 50 characters)",
    newIndication: "Is new",
    invested: "Invested",
    noLogs: "NO LOGS",
    noRatWarning: "Buy a rat to access this trip",
    noData: "No data",
    now: "now",
    onChainBalance: "On-chain Balance",
    online: "online",
    owner: "Owner",
    pastRatsCount: "Past Rats",
    payout: "Payout",
    player: "Player",
    playerId: "PLAYER ID:",
    past: "Past",
    pastTrips: "Past trips",
    profit: "Profit",
    portfolio: "Portfolio",
    rat: "Rat",
    ratAmountKilled: "Rats killed",
    ratBeingRevived:
      "RAT BEING REVIVED FROM DEEP DRUG INDUCED COMA.\nEVERYTHING IS NORMAL.\nPLEASE STAND BY...",
    ratCreationTimeout: "Timeout waiting for rat creation",
    ratHallucinatoryState: "RAT STILL IN HALLUCINATORY STATE.\nPLEASE STAND BY...",
    ratId: "RAT ID:",
    rats: "Rats",
    ratValue: "Rat value",
    readyQuestion: "Ready?",
    requestTokens: "Request tokens from the contract",
    revokeApproval: "Revoke approval",
    revokeApprovalInstruction: "Revoke contract spending approval (set to 0)",
    riskHi: "HI",
    riskLow: "LOW",
    riskMid: "MID",
    riskNightmare: "NITEMARE",
    riskProfile: "Risk profile:",
    riskUnclear: "UNCLEAR",
    selectCategoryPrompt: "Please select a category for your trip",
    selectFolder: "Select Folder",
    send: "Send",
    sendRatToTrip: "Send rat to trip",
    sent: "sent",
    showDepletedTrips: "show depleted trips",
    sign: "SIGN",
    siteTitle: "RAT.FUN",
    sortByBalance: "sort by balance",
    sortByKillCount: "sort by kill count",
    sortByPopularity: "sort by popularity",
    sortByVisit: "sort by visit",
    sortChronologically: "sort chronologically",
    spawn: "Spawn",
    spawned: "Spawned",
    stop: "Stop",
    supervisorModeActivated: "Supervisor mode activated",
    survived: "SURVIVED",
    thereAreTrips: (count: number): string => `There are ${count} trips`,
    tokens: "Tokens",
    tokensAvailable: "This is available tokens in your wallet",
    toTrip: "to trip #",
    toTripShort: "to trip",
    topBarMarqueeText: "THERE IS NO LUCK. ONLY SKILL. THERE ARE NO BAD TRIPS, ONLY BAD RATS.",
    topMarqueeText: "RAT.FUN IS A GAME OF SKILL.",
    transactionInProgress: "Transaction in progress...",
    traumwertSteuer: "TraumwertSteuer",
    trip: "Trip",
    tripBalance: "Trip balance",
    tripCreationCostLabel: "TRIP CREATION COST",
    tripDescription: "Trip Description",
    tripGotDepleted: (index: number): string => `Trip #${index} got depleted`,
    tripLogs: "TRIP LOGS",
    tripPrompt: "TRIP PROMPT:",
    tripReport: "TRIP REPORT",
    trips: "Trips",
    tripsLabel: "Trips:",
    tripSitters: "TRIP SITTERS",
    unlockAdmin: "Unlock Admin",
    unlockAdminInstruction: "Unlock cashboard",
    unlockAdminMessage: "Unlock admin to start creating trips",
    unlockingAdmin: "Unlocking Admin",
    unlock: "Unlock",
    unknown: "unknown",
    valueLabel: "VALUE",
    visits: "Visits",
    waitForTokens: "You do not have $RAT tokens. Come back later...",
    waitBlocks: (blocks: number): string => `Wait ${blocks} blocks`,
    walletType: "Wallet Type",
    worldAddress: "World address",
    you: "You",
    youAreSet: (name: string): string => `${name}, you are set!`,
    youCreatedTrip: (index: number): string => `You created trip #${index}`,
    youIndication: (name: string) => `This is you: ${name}`,
    youLiquidatedTrip: (index: number): string => `You liquidated trip #${index}`,
    yourName: "YOUR NAME",
    youWillRecover: "You will recover",
    allIsFine: "ALL IS FINE.\n JUST ONE MOMENT.\n WE VALUE YOUR PATIENCE."
  }
} as const

type Locale = keyof typeof stringsData
type Strings = (typeof stringsData)[Locale]

let locale: Locale = "en-US"

export const strings: Strings = stringsData[locale]
