<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 RAT_FinalModel_01.glb
-->

<script>
  import { T } from "@threlte/core"
  import { useGltf } from "@threlte/extras"
  import { useTask } from "@threlte/core"

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  let rotation = $state(0)

  useTask(d => {
    rotation += d
  })

  const gltf = useGltf("/models/RAT_FinalModel_01.glb")
</script>

<T.Group bind:ref dispose={false} {...props}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      castShadow
      rotation.z={rotation}
      geometry={gltf.nodes.Small_Up_NONMIRRORED.geometry}
      material={gltf.materials.Rat}
      position={[0, -0.5, 1.91]}
      scale={1}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
