<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 src/svelte/public/models/RatAnimated.glb
-->

<script>
  import { Group } from "three"

  import { T } from "@threlte/core"
  import { useGltf, useGltfAnimations, useDraco } from "@threlte/extras"
  import CustomRenderer from "@components/3D/World/CustomRenderer/CustomRenderer.svelte"

  let {
    fallback,
    error,
    children,
    moving,
    ref = $bindable(),
    ...props
  } = $props()

  ref = new Group()

  const dracoLoader = useDraco()
  const gltf = useGltf("/models/RatAnimated.glb", { dracoLoader })

  export const { actions, mixer } = useGltfAnimations(gltf, ref)

  $effect(() => {
    $actions["Walk.Stepped"]?.play()
  })

  $effect(() => {
    $actions?.["Walk.Stepped"]?.setEffectiveTimeScale(moving.current)
  })
</script>

<CustomRenderer
  effects={{
    godotFishEye: true,
    crt: {
      scan: 2,
      warp: 1,
    },
  }}
/>

<T is={ref} dispose={false} {...props}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group rotation.y={Math.PI / 2} name="Scene">
      <!-- <T.Mesh rotation.x={Math.PI / 2}>
        <T.CylinderGeometry args={[0, 0.2, 2]} />
        <T.MeshNormalMaterial />
      </T.Mesh> -->
      <T.Group name="RIG-Rat_Rigify_Stepped">
        <T is={gltf.nodes.root} />
        <T is={gltf.nodes["MCH-torsoparent"]} />
        <T is={gltf.nodes["MCH-Shoulder_ikparentL001"]} />
        <T is={gltf.nodes["MCH-Shoulder_ik_targetparentL"]} />
        <T is={gltf.nodes["MCH-Shoulder_ikparentR001"]} />
        <T is={gltf.nodes["MCH-Shoulder_ik_targetparentR"]} />
        <T is={gltf.nodes["MCH-Shin_ikparentL"]} />
        <T is={gltf.nodes["MCH-Hip_ik_targetparentL"]} />
        <T is={gltf.nodes["MCH-Shin_ikparentR"]} />
        <T is={gltf.nodes["MCH-Hip_ik_targetparentR"]} />
        <T.SkinnedMesh
          castShadow
          name="Small_Up_NONMIRRORED001"
          geometry={gltf.nodes.Small_Up_NONMIRRORED001.geometry}
          material={gltf.materials.Rat}
          skeleton={gltf.nodes.Small_Up_NONMIRRORED001.skeleton}
        />
      </T.Group>
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T>
