// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { GameConfig, GameConfigData } from "./tables/GameConfig.sol";
import { ExternalAddressesConfig, ExternalAddressesConfigData } from "./tables/ExternalAddressesConfig.sol";
import { LevelList } from "./tables/LevelList.sol";
import { WorldEvent, WorldEventData } from "./tables/WorldEvent.sol";
import { Name } from "./tables/Name.sol";
import { EntityType } from "./tables/EntityType.sol";
import { CreationBlock } from "./tables/CreationBlock.sol";
import { LastVisitBlock } from "./tables/LastVisitBlock.sol";
import { Health } from "./tables/Health.sol";
import { Dead } from "./tables/Dead.sol";
import { Traits } from "./tables/Traits.sol";
import { Inventory } from "./tables/Inventory.sol";
import { Level } from "./tables/Level.sol";
import { AchievedLevels } from "./tables/AchievedLevels.sol";
import { MasterKey } from "./tables/MasterKey.sol";
import { Index } from "./tables/Index.sol";
import { Balance } from "./tables/Balance.sol";
import { Value } from "./tables/Value.sol";
import { CurrentRat } from "./tables/CurrentRat.sol";
import { PastRats } from "./tables/PastRats.sol";
import { Owner } from "./tables/Owner.sol";
import { VisitCount } from "./tables/VisitCount.sol";
import { KillCount } from "./tables/KillCount.sol";
import { Prompt } from "./tables/Prompt.sol";
import { RoomCreationCost } from "./tables/RoomCreationCost.sol";
import { IsSpecialRoom } from "./tables/IsSpecialRoom.sol";
import { MaxValuePerWin } from "./tables/MaxValuePerWin.sol";
import { LevelMinBalance } from "./tables/LevelMinBalance.sol";
import { LevelMaxBalance } from "./tables/LevelMaxBalance.sol";
