// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { GameConfig, GameConfigData } from "./tables/GameConfig.sol";
import { Name } from "./tables/Name.sol";
import { EntityType } from "./tables/EntityType.sol";
import { Health } from "./tables/Health.sol";
import { Intelligence } from "./tables/Intelligence.sol";
import { Strength } from "./tables/Strength.sol";
import { Sanity } from "./tables/Sanity.sol";
import { Luck } from "./tables/Luck.sol";
import { Trait } from "./tables/Trait.sol";
import { Currency } from "./tables/Currency.sol";
import { OwnedRat } from "./tables/OwnedRat.sol";
import { Owner } from "./tables/Owner.sol";
import { RoomPrompt } from "./tables/RoomPrompt.sol";
import { RoomIndex } from "./tables/RoomIndex.sol";
