import { CURRENCY_SYMBOL } from "$lib/modules/ui/constants"

export const enUS = {
  address: "Address",
  admin: "TRIPS LAB",
  adminInstruction: (price: number) =>
    `Unlock access to our rat-a-licious TRIPS LAB for ${price} ${CURRENCY_SYMBOL}.<br>Lets you create bespoke TRIPS through a Bloomberg-style terminal for the mentally deranged.<br>Results may vary.`,
  action: "Action",
  all: "All",
  activeProfit: "Active profit",
  adminUnlocked: "Admin unlocked",
  adminUnlockedMessage: "You unlocked the TRIPS LAB",
  ago: "ago",
  alive: "Alive",
  active: "Active",
  activeTrips: "Active TRIPS",
  allowance: "Allowance",
  approveAllowance: "Approve max allowance",
  approveAllowanceInstruction: "Allow the contract to spend on your behalf",
  approvingAllowance: "Approving allowance",
  currentAllowance: "Current allowance",
  insufficientAllowance: "You do not have enough allowance to complete this action.",
  manageAllowance: "Manage Allowance",
  manageAllowanceDescription:
    "Set how much the game contract is allowed to spend on your behalf. This is required to have fun.",
  newAllowance: "NEW ALLOWANCE",
  setAllowance: "Set Allowance",
  settingAllowance: "Authorizing machine",
  authorFullTitle: "Moving Castles GmbH",
  totalValue: "Total value",
  totalValueExplanation: "The total value of your rat is a sum of your health and PSYCHO OBJECTS",
  back: "Back",
  balance: "Balance",
  blockNumber: "BlockNumber",
  bottomMarqueeText: "THERE ARE NOT BAD TRIPS, ONLY BAD RATS.",
  buyRat: "Buy Rat",
  buySomeTokens: `Buy some ${CURRENCY_SYMBOL}`,
  buyTokens: (amount: number): string => `Buy ${amount} ${CURRENCY_SYMBOL} for 0.001ETH`,
  cancel: "Abort",
  causeOfDeathShort: "CoD",
  confirm: "Confirm",
  confirmLiquidationMessage: (name: string): string =>
    `Are you sure you want to cash out? ${name} will be terminated in the process.`,
  comeDown: "COME DOWN",
  connectWallet: "Connect wallet",
  connectedWallet: "Connected wallet",
  confirmLiquidateTripPrompt: (index: number): string =>
    `Are you sure you want to CASH OUT TRIP #${index}?`,
  cost: "Cost:",
  createdTrip: "created TRIP",
  creatingTripIn: "Filing TRIP under:",
  creationBlock: "Create @",
  creationCost: "Creation Cost",
  createTrip: "Create Trip",
  createTripButton: "Create TRIP",
  createTripPlaceholder: "You're creating a TRIP...",
  creator: "Operator",
  currentRat: "Current Rat",
  debug: "Debug",
  deployed: "deployed",
  destroyedTrip: "destroyed TRIP",
  died: "DIED",
  dieFromTrip: "die from TRIP #",
  dieInTrip: "die in TRIP",
  diedTripping: "died tripping #",
  disconnectWallet: "Disconnect wallet",
  egoDeathExplanation: `!!! ATTENTION OPERATOR !!! TRIPS are untested substances and might cause extreme death to your rat!`,
  empty: "Empty",
  enjoySkillfully: "ENJOY SKILLFULLY",
  events: "Events",
  environment: "Environment",
  erc20Balance: "ERC20 Balance",
  filter: "Filter",
  fomoAlertBalance: (balance: number): string => `FOMO ALERT! Balance is ${balance}`,
  forceRatLiquidation: "Force CASH OUT rat",
  getFreeTokens: (amount: number): string => `Get ${amount} free ${CURRENCY_SYMBOL}`,
  gettingRat: "Getting your rat...",
  gettingTokens: "Getting tokens",
  getTokens: (amount: number): string => `Get ${amount} $RAT`,
  graph: "Graph",
  hasTokens: "Has tokens",
  health: "HEALTH",
  home: "Home",
  hot: "HOT",
  insufficientBalance: "Insufficient balance",
  inventory: "Inventory",
  issuingMemberCard: "Connecting Operator",
  killInProgress: "KILLING IN PROGRESS",
  kills: "Kills",
  lastVisit: "Last Visit",
  lastVisitedSecondsAgo: (seconds: number): string => `Last visited ${seconds} seconds ago`,
  let: "let",
  liquidate: "CASH OUT",
  liquidated: "CASHED OUT",
  liquidatingTrip: "CASHING OUT TRIP",
  log: "Log",
  liquidateRatButtonText: (value: number) => `CASH OUT (${value}${CURRENCY_SYMBOL})`,
  liquidateRatInstruction: "Cash out the total value of your rat, for a small fee",
  liquidationBlockShort: "Liq. @",
  liquidationValueShort: "Liq. Val.",
  loadingMsg: "LoadingMsg",
  loadingPercentage: "Loading%",
  locked: "locked",
  masterKey: "TRIPS LAB unlocked",
  maxReward: "MAY PAYOUT",
  maxValuePerWin: "MAX REWARD",
  maxValuePerWinLabel: "MAX VALUE PER WIN",
  messageCannotBeEmpty: "Message cannot be empty",
  minRatValueToEnter: "Min rat value to enter",
  music: "Music",
  musicOn: "Music: ON",
  musicOff: "Music: OFF",
  minRatValueToTrip: "MIN RAT VALUE TO TRIP",
  minRatValueWarning: (value: number): string => `Rat value too low (at least ${value})`,
  moveOn: "MOVE ON",
  name: "Name",
  nameCannotBeEmpty: "Name cannot be empty",
  nameTooLong: "Name is too long (maximum 50 characters)",
  newer: "newer",
  newIndication: "Is new",
  invested: "Invested",
  itemsNone: "no PSYCHO OBJECTS",
  logsNone: "no logs",
  noRatWarning: "Buy a rat to access this TRIP",
  noData: "No data",
  now: "now",
  onChainBalance: "On-chain Balance",
  online: "online",
  older: "older",
  owner: "Owner",
  pastRatsCount: "Past Rats",
  payout: "Payout",
  player: "Player",
  playerId: "PLAYER ID:",
  inventoryName: "PSYCHO OBJECT INVENTORY",
  past: "Past",
  pastTrips: "Past TRIPS",
  profit: "Profit",
  portfolio: "Portfolio",
  itemExplanation:
    "PSYCHO OBJECTS are materializations of mental items acquired tripping. Nobody really knows how they work, but they are 1000% real, definitely NOT hallucinations",
  rat: "Rat",
  ratAmountKilled: "Rats killed",
  ratBeingRevived:
    "RAT BEING REVIVED FROM DEEP DRUG INDUCED COMA.\nEVERYTHING IS NORMAL.\nPLEASE STAND BY...",
  ratCreationTimeout: "Timeout waiting for rat creation",
  ratHallucinatoryState: "RAT STILL IN HALLUCINATORY STATE.\nPLEASE STAND BY...",
  ratId: "RAT ID:",
  rats: "Rats",
  ratValue: (name: string) => name + "'s total value",
  readyQuestion: "Ready?",
  requestTokens: "Request tokens from the contract",
  revokeApproval: "Revoke approval",
  revokeApprovalInstruction: "Revoke contract spending approval (set to 0)",
  riskHi: "HI",
  riskLow: "LOW",
  riskMid: "MID",
  riskNightmare: "NITEMARE",
  riskProfile: "Risk profile:",
  riskUnclear: "UNCLEAR",
  selectCategoryPrompt: "Please select a category for your TRIP",
  selectFolder: "Select TRIP category",
  send: "Send",
  sendRatToTrip: "TRIP",
  sent: "sent",
  showDepletedTrips: "show depleted TRIPS",
  sign: "SIGN",
  siteTitle: "RAT.FUN",
  sortByBalance: "sort by balance",
  sortByKillCount: "sort by kill count",
  sortByPopularity: "sort by popularity",
  sortByVisit: "sort by visit",
  sortChronologically: "sort chronologically",
  spawn: "Spawn",
  spawned: "Spawned",
  stop: "Stop",
  supervisorModeActivated: "Supervisor mode activated",
  survived: "SURVIVED",
  thereAreTrips: (count: number): string => `There are ${count} TRIPS`,
  tokens: "Tokens",
  tokensAvailable: "This is available tokens in your wallet",
  tokensAvailableLabel: "Available",
  toTrip: "OPEN FULL STATISTICS FOR TRIP #",
  toTripShort: "TO STATISTICS",
  topBarMarqueeText: "THERE IS NO LUCK. ONLY SKILL. THERE ARE NO BAD TRIPS, ONLY BAD RATS.",
  topMarqueeText: "RAT.FUN IS A GAME OF SKILL.",
  transactionInProgress: "Transaction in progress...",
  traumwertSteuer: "TraumwertSteuer",
  traumwertSteuerExplanation: (percentage: number): string => `${percentage}% corporate tax`,
  trip: "Trip",
  tripBalance: "Trip balance",
  tripCreationCostLabel: "Trip creation investment",
  tripDescription: "Expected symptoms",
  tripGotDepleted: (index: number): string => `Trip #${index} got depleted`,
  tripLogs: "TRIP LOGS",
  tripPrompt: "TRIP PROMPT:",
  tripReport: "TRIP REPORT",
  trips: "TRIPS",
  tripsLabel: "TRIPS:",
  tripSitters: "TRIP SITTERS",
  unlockAdmin: "Unlock TRIPS LAB",
  unlockAdminInstruction: "Unlock TRIPS LAB",
  unlockAdminLoading: "Unlocking TRIPS LAB",
  unlock: "Unlock",
  unknown: "unknown",
  valueLabel: "VALUE",
  visits: "Visits",
  waitForTokens: "🫵YOU🫵 do not have $RAT tokens. 🫵YOU🫵 will come back on tuesday.",
  waitBlocks: (blocks: number): string => `Wait ${blocks} blocks`,
  walletType: "Wallet Type",
  worldAddress: "World address",
  you: "You",
  youAreSet: (name: string): string => `${name}, you are set!`,
  youCreatedTrip: (index: number): string => `You created TRIP #${index}`,
  youIndication: (name: string) => `This is you: ${name}`,
  youLiquidatedTrip: (index: number): string => `You CASHED OUT TRIP #${index}`,
  yourName: "YOUR NAME",
  youWillRecover: "You will recover",
  allIsFine: "ALL IS FINE.\n JUST ONE MOMENT.\n WE VALUE YOUR PATIENCE.",
  tripHeader: "Select a category",
  tripHeaderNoRat: "Buy rat to select TRIP.",
  unlockAdminHeader: "Unlock TRIPS LAB",
  unlockAdminMessage:
    "Lets you create bespoke TRIPS through a Bloomberg-style terminal for the mentally deranged. Results may vary.",
  // Trip processing popup messages
  tripProcessingFirst: "ALL IS FINE.\n JUST ONE MOMENT.\n WE VALUE YOUR PATIENCE.",
  tripProcessingSecond: "RAT STILL IN HALLUCINATORY STATE.\nPLEASE STAND BY...",
  tripProcessingThird: "RAT BEING REVIVED FROM DEEP DRUG INDUCED COMA...",
  // Trip setup messages
  tripSetupPresents: "*** RAT.FUN SCIENTIFIC INSTRUMENTS LLC PRESENTS ***",
  tripSetupWarning: "WARNING",
  tripSetupExperimental: "THIS IS AN EXPERIMENTAL EXPERIENCE AND MAY BE LETHAL",
  tripSetupLiability: "ABSOLUTELY NO LIABITITY FOR ANY PSYCHOLOGICAL MUTILATION",
  tripSetupWarranty:
    "WARRANTY VOIDED. EXTENDS TO THE PLAYER, RAT SUBJECT AND EVERY OTHER ENTITY IN THE WORLD.",
  tripSetupResponsibility: "BY NOT DESTROYING THIS MACHINE YOU ACCEPT FULL RESPONSIBILITY",
  tripSetupFault: "EVERYTHING IS YOUR FAULT",
  tripSetupSkull: "ALL EVENTS HAPPEN INSIDE THE SKULL OF THE RAT",
  tripSetupSetting: "Setting up TRIP: ",
  tripSetupPneumatic: "= Pneumatic system engaged",
  tripSetupConveyed: "= Rat conveyed to TRIP chamber",
  tripSetupDiaper: "= PETA approved Diaper attached",
  tripSetupProbes: "= Intercranial probes attached",
  tripSetupDosed: "= Rat dosed with 44mg of Slopamine",
  tripSetupInitiated: "= Trip initiated: ",
  // Trip report
  tripReportStart: "TRIP REPORT // START",
  tripReportEnd: "TRIP REPORT // END",
  balanceLabel: "Balance",
  dead: "DEAD",
  // Spawn error messages
  somethingWentWrong: "Something went wrong",
  errorOccurred: "An error occurred during the spawn process. Please try again.",
  startOver: "Start over",
  // Session setup
  sessionSetup: "Session Setup",
  sessionSetupDescription:
    "Create a secure session to interact with the game without signing every transaction.",
  setupSession: "BRAINDUMP MEMORIES",
  // Online users
  onlinePlayers: "Online players",
  connecting: "Connecting...",
  onlinePlayersCount: (count: number): string => `Online Players (${count})`,
  operator: "Operator",
  noPlayersOnline: "No players online",
  // Settings
  playerNotifications: "Player Notifications",
  tripNotifications: "Trip Notifications",
  language: "Language",
  // Loading sequence
  loadingCompany: "RAT.FUN SCIENTIFIC INSTRUMENTS LLC",
  loadingCopyright: "(c) 2034 Sexc-hell island, Kowloon, Hong Kong",
  loadingRights: "All Rights Reserved in accordance with Maritime Law",
  loadingDissociated: "FULLY DISSOCIATED AND DISOWNED SISTER COMPANY OF MOVING CASTLES GMBH",
  loadingPatent: "Patent pending in all non-aligned territories",
  loadingTrademarks: "FUN and RAT are registered trademarks of RAT.FUN SCIENTIFIC INSTRUMENTS LLC",
  loadingAgreement:
    "BY READING THIS TEXT YOU AGREE TO BE BOUND BY THE TERMS OF THE AGREEMENT AND FORFEIT YOUR HUMAN RIGHTS",
  loadingBoot: "BOOTING SLOP MACHINE...",
  // Introduction messages
  introductionStep1: "Gooood moooooorning **OPERATOR**!",
  introductionStep2: "Welcome to our rat controlled remote viewing **SLOP MACHINE**.",
  introductionStep3: "If operated skilfully this machine will bring you great riches!",
  introductionStep4:
    "Pump your rats with drugs and send them tripping, then cash out tokens by exploiting their success.",
  introductionStep5: "I can feel your dopamine injectors tingling! What are you waiting for?",
  introductionButtonOk: "OK",
  introductionButtonReady: "I AM OPERATOR"
} as const
