import { CURRENCY_SYMBOL } from "$lib/modules/ui/constants"

export const itBR = {
  address: "indirizzio",
  admin: "PANNELL DEI $OLDI",
  adminInstruction: (price: number) => `sblocka la feature + topa fra no cap
    \nper ${price} ${CURRENCY_SYMBOL}. ti fa craftare trip kustom\nattraverso terminal bloomberg-mode ma\nper psyko bro. risultati boh lol.`,
  action: "Aczion",
  all: "tutt",
  activeProfit: "profitt attiv",
  adminUnlocked: "admin unlockato fr",
  adminUnlockedMessage: "Hai unlockato il Pannell dei Soldi zio gg",
  ago: "fa tipo",
  alive: "viv fr",
  active: "attiv",
  activeTrips: "trip attiv",
  allowance: "permess",
  approveAllowance: "approva permess massiv",
  approveAllowanceInstruction: "fai spendà al kontract per te bro",
  approvingAllowance: "approvand permess",
  currentAllowance: "permess kurrent",
  insufficientAllowance: "nn hai abbastanz permess x fare sta kosa bro.",
  manageAllowance: "gestisce Permess",
  manageAllowanceDescription:
    "setta kwanto il game kontratt puo spendà x te. obbligatorio x divertirsi zio.",
  newAllowance: "PERMESS NUOV",
  setAllowance: "setta Permess",
  settingAllowance: "settand Permess",
  authorFullTitle: "Moving Castles GmbH",
  totalValue: "valuta total",
  totalValueExplanation: "il valuta total del tuo rat è somma de HP e PsychoRoba bro",
  back: "tornaindietro",
  balance: "€€€",
  blockNumber: "NumeroBlokko",
  bottomMarqueeText: "NON CI STA TRIP BRUTTISSIMI, SOLO RAT BRUTTISSIMI FR FR.",
  buyRat: "BUYYA RAT",
  buySomeTokens: `buyya un po de ${CURRENCY_SYMBOL}`,
  buyTokens: (amount: number): string => `buyya ${amount} ${CURRENCY_SYMBOL} x 0.001ETH`,
  cancel: "abort",
  causeOfDeathShort: "CoD",
  confirm: "konferma",
  confirmLiquidationMessage: (name: string): string =>
    `sei sikuro de kasciare? ${name} verra terminat nel process bro no cap.`,
  comeDown: "SCEND GIU ZIO",
  connectBurner: "konnetti Burner",
  connectWallet: "konnetti wallett",
  connectedWallet: "wallett konness",
  confirmLiquidateTripPrompt: (index: number): string =>
    `sei sikuro de likwidar trip #${index}?`,
  cost: "€:",
  createdTrip: "trip kraftat",
  creatingTripIn: "kraftand trip in:",
  creationBlock: "kraftat @",
  creationCost: "€ Kreazion",
  createTrip: "Krafta Trip",
  createTripButton: "krafta trip",
  createTripPlaceholder: "stai kraftando un trip bro...",
  creator: "kreator",
  currentRat: "rat kurrent",
  debug: "debugga",
  deployed: "deployyat gg",
  destroyedTrip: "trip destroyat rip",
  died: "MORT RIP",
  dieFromTrip: "muor dal trip #",
  dieInTrip: "muor nel trip",
  diedTripping: "mort trippand #",
  disconnectWallet: "diskonnetti wallett",
  egoDeathExplanation: `!!! ATTENZION OPERATOR !!!\ni trip sono sostanz non testat e\nposso kausa morte extrem al tuo rat bro!`,
  empty: "vuotissim",
  enjoySkillfully: "GODI KON SKILLA",
  events: "eventi",
  environment: "ambiente",
  erc20Balance: "€€€ ERC20",
  filter: "filtr",
  fomoAlertBalance: (balance: number): string => `ALARM FOMO! €€€ è ${balance}`,
  forceRatLiquidation: "likwida rat kon forza",
  getFreeTokens: (amount: number): string => `prendi ${amount} ${CURRENCY_SYMBOL} gratis fra no cap`,
  gettingRat: "prend il tuo rat zio...",
  gettingTokens: "prend token...",
  getTokens: (amount: number): string => `prendi ${amount} $RAT`,
  graph: "grafik",
  hasTokens: "ha token",
  health: "HP",
  home: "kasa",
  hot: "FOCO",
  insufficientBalance: "€€€ insuff",
  inventory: "inventar",
  issuingMemberCard: "emettend tessera member",
  killInProgress: "KILLAGGIO IN PROGRESS",
  kills: "kill",
  lastVisit: "ultima visit",
  lastVisitedSecondsAgo: (seconds: number): string => `visitat ${seconds} sec fa`,
  let: "let",
  liquidate: "likwida",
  liquidated: "likwidat",
  liquidatingTrip: "likwidand trip",
  log: "logg",
  liquidateRatButtonText: "KA$H OUT",
  liquidateRatInstruction: "kascia il valuta total del tuo rat, kon piccol fee zio",
  liquidationBlockShort: "Lik. @",
  liquidationValueShort: "Val. Lik.",
  loadingMsg: "MsgLoadand",
  loadingPercentage: "loadand%",
  locked: "lokkat",
  masterKey: "Pannell Soldi unlockato gg",
  maxReward: "PAYOUT maybe",
  maxValuePerWin: "MAX PAYOUT",
  maxValuePerWinLabel: "VAL MAX X WIN",
  messageCannotBeEmpty: "msg non puo esser vuot bro",
  minRatValueToEnter: "val min rat x entrar",
  music: "muzika",
  musicOn: "muzika: ON",
  musicOff: "muzika: OFF",
  minRatValueToTrip: "VAL MIN RAT X TRIPPAR",
  minRatValueWarning: (value: number): string => `val rat tropp bass (almeno ${value})`,
  moveOn: "MUOVIT BRO",
  name: "nom",
  nameCannotBeEmpty: "nom non puo esser vuot",
  nameTooLong: "nom tropp lung (max 50 chars)",
  newIndication: "è nuovo fra",
  invested: "investit",
  noLogs: "ZERO LOGG",
  noRatWarning: "buyya rat x accessar sto trip bro",
  noData: "zero data",
  now: "ades",
  onChainBalance: "€€€ onchain",
  online: "onlain",
  owner: "proprietar",
  pastRatsCount: "rat passat",
  payout: "payout",
  player: "playator",
  playerId: "ID PLAYATOR:",
  psychoInventory: "PsychoRoba",
  past: "passat",
  pastTrips: "trip passat",
  profit: "profitt",
  portfolio: "portfol",
  psychoObjectExplanation:
    "i PsychoRoba sono materializazion de oggett mental akwisit trippando. nessun sa kom funziona, ma son 1000% real, NON allucin bro fr fr",
  rat: "rat",
  ratAmountKilled: "rat killat",
  ratBeingRevived:
    "RAT IN REVIVAL DA KOMA INDOTT DA DROGA.\nTUTTO NORMALISSIM BRO.\nPLS ASPETTA...",
  ratCreationTimeout: "timeout aspettand kreazion rat rip",
  ratHallucinatoryState: "RAT ANKOR IN STATO ALLUCINATOR.\nPLS ASPETTA...",
  ratId: "ID RAT:",
  rats: "rat",
  ratValue: (name: string) => "val total de " + name,
  readyQuestion: "pront?",
  requestTokens: "rikied token dal kontratt",
  revokeApproval: "revoka approva",
  revokeApprovalInstruction: "revoka approva spend kontratt (setta a 0)",
  riskHi: "HIGH",
  riskLow: "LOW",
  riskMid: "MID",
  riskNightmare: "NIGHTMAR",
  riskProfile: "profil risk:",
  riskUnclear: "BOH",
  selectCategoryPrompt: "seleziona kategor x il tuo trip fra",
  selectFolder: "seleziona kategor trip",
  send: "invia",
  sendRatToTrip: "TRIPPA",
  sent: "inviat",
  showDepletedTrips: "mostra trip esaurit",
  sign: "FIRMA",
  siteTitle: "RAT.FUN",
  sortByBalance: "sort by €€€",
  sortByKillCount: "sort by kill kount",
  sortByPopularity: "sort by pop",
  sortByVisit: "sort by visit",
  sortChronologically: "sort kronologik",
  spawn: "spawna",
  spawned: "spawnat gg",
  stop: "stop",
  supervisorModeActivated: "supervisor mode attivat",
  survived: "SOPRAVVISSUT GG",
  thereAreTrips: (count: number): string => `ci sta ${count} trip`,
  tokens: "token",
  tokensAvailable: "questi token disponibil nel wallett tuo",
  toTrip: "al trip #",
  toTripShort: "al trip",
  topBarMarqueeText: "NON C'E LUCK. SOLO SKILLA. NON CI STA TRIP BRUTTI, SOLO RAT BRUTTI FR.",
  topMarqueeText: "RAT.FUN È UN GAME DE SKILLA NO CAP.",
  transactionInProgress: "transazion in progress...",
  traumwertSteuer: "TraumwertSteuer",
  traumwertSteuerExplanation: (percentage: number): string => `${percentage}% tax korporativ`,
  trip: "trip",
  tripBalance: "€€€ trip",
  tripCreationCostLabel: "invest kreazion trip",
  tripDescription: "sintomi prevvist",
  tripGotDepleted: (index: number): string => `trip #${index} si è esaurit rip`,
  tripLogs: "LOGG TRIP",
  tripPrompt: "PROMPT TRIP:",
  tripReport: "REPORT TRIP",
  trips: "trip",
  tripsLabel: "trip:",
  tripSitters: "TRIP SITTER",
  unlockAdmin: "unlokka Admin",
  unlockAdminInstruction: "unlokka Pannell Soldi",
  unlockingAdmin: "unlokkand Admin",
  unlock: "unlokka",
  unknown: "boh",
  valueLabel: "VAL",
  visits: "visit",
  waitForTokens: "🫵TU🫵 nn hai token $RAT. 🫵TU🫵 tornerai dopo zio fr.",
  waitBlocks: (blocks: number): string => `aspetta ${blocks} blokk`,
  walletType: "tipo wallett",
  worldAddress: "indirizzio world",
  you: "tu",
  youAreSet: (name: string): string => `${name}, sei appost fra gg!`,
  youCreatedTrip: (index: number): string => `hai kraftat trip #${index} gg`,
  youIndication: (name: string) => `questo sei tu bro: ${name}`,
  youLiquidatedTrip: (index: number): string => `hai likwidat trip #${index}`,
  yourName: "IL TUO NOM",
  youWillRecover: "ti riprenderai zio no cap",
  allIsFine: "TUTTO APPOST.\n SOLO 1 ATTIM.\n GRAZIE X PAZIENZ.",
  tripHeader: "seleziona kategor",
  tripHeaderNoRat: "buyya rat x selezionar trip.",
  unlockAdminHeader: "unlokka Pannell Soldi",
  unlockAdminMessage:
    "ti fa kraftare trip kustom attraverso terminal bloomberg-mode x gente fuor de testa. risultati boh lol.",
  // Trip processing popup messages
  tripProcessingFirst: "TUTTO APPOST.\n SOLO 1 ATTIM.\n GRAZIE X PAZIENZ.",
  tripProcessingSecond: "RAT ANKOR IN STATO ALLUCINATOR.\nPLS ASPETTA...",
  tripProcessingThird: "RAT IN REVIVAL DA KOMA INDOTT DA DROGA...",
  // Trip setup messages
  tripSetupPresents: "*** RAT.FUN STRUMENTI SCIENTIFIK LLC PRESENTA ***",
  tripSetupWarning: "ATTENZION",
  tripSetupExperimental: "QUESTA È SPERIENZ SPERIMENTAL E PUO ESSER LETAL",
  tripSetupLiability: "ASSOLUTAMENT ZERO RESPONSABILIT X MUTILAZION PSIKOLOGIK",
  tripSetupWarranty:
    "GARANZIA ANNULLAT. SI ESTENDE AL PLAYATOR, RAT SOGGETT E TUTT GLI ALTR ENTITA NEL MOND.",
  tripSetupResponsibility: "NON DISTRUGGEND STA MAKKINA AKKETTI PIENA RESPONSABILIT",
  tripSetupFault: "TUTT È KOLPA TUA BRO",
  tripSetupSkull: "TUTT GLI EVENT AKKADONO DENTR IL KRANEO DEL RAT",
  tripSetupSetting: "settand trip: ",
  tripSetupPneumatic: "= sistem pneumatik attivat",
  tripSetupConveyed: "= rat trasportat in kamera trip",
  tripSetupDiaper: "= pannolin approvat PETA attakkat",
  tripSetupProbes: "= sonde intrakranial attakkat",
  tripSetupDosed: "= rat dosat kon 44mg de Slopamina",
  tripSetupInitiated: "= trip iniziat: ",
  // Trip report
  tripReportStart: "REPORT TRIP // INIZIO",
  tripReportEnd: "REPORT TRIP // FINE",
  balanceLabel: "€€€",
  dead: "MORT",
  // Spawn error messages
  somethingWentWrong: "qualkkosa è andat mal",
  errorOccurred: "error akkadut durante il process de spawn. riprova zio.",
  startOver: "rikominca",
  // Session setup
  sessionSetup: "setup sessione",
  sessionSetupDescription: "krea sessione sikur x interagir kon il game senza firmar ogni transazion.",
  setupSession: "setta sessione",
  // Online users
  onlinePlayers: "playator onlain",
  connecting: "konnettend...",
  onlinePlayersCount: (count: number): string => `Playator Onlain (${count})`,
  noPlayersOnline: "zero playator onlain",
  // Settings
  playerNotifications: "Notifik Playator",
  tripNotifications: "Notifik Trip",
  language: "Lingua",
  // Loading sequence
  loadingCompany: "RAT.FUN STRUMENTI SCIENTIFIK LLC",
  loadingCopyright: "(c) 2034 Sexc-hell island, Kowloon, Hong Kong",
  loadingRights: "tutti i diritti riservat in akkord kon la legge marittim",
  loadingDissociated: "KOMPLETAMENT DISSOÇIAT E DISOWN SISTER KOMPANY DE MOVING CASTLES GMBH",
  loadingPatent: "Patent pendente in tutt i territori non-allineati",
  loadingTrademarks: "FUN e RAT sono marki registrat de RAT.FUN STRUMENTI SCIENTIFIK LLC",
  loadingAgreement:
    "LEGGEND QUEST TESTO AKKETTI DE ESSER VINKOLAT AI TERMINI DELL AKKORD E FORFETTI I TUA DIRITTI UMAN BRO FR FR",
  loadingBoot: "BOOTTAND MAKKINA SLOP...",
  // Introduction messages
  introductionStep1: "Buoooongiornooooo **OPERATOR** zio!",
  introductionStep2: "benvenut alla nostra **MAKKINA SLOP** kontroltat da rat fr fr.",
  introductionStep3: "se operat kon skilla sta makkina ti portera rikkezz immens bro no cap!",
  introductionStep4:
    "pompa i tuo rat kon droghe e inviali trippando, poi kascia token sfruttando il lor sukkess zio gg.",
  introductionStep5: "sent i tuo iniettori de dopamina formikolà! ke aspett fra?",
  introductionButtonOk: "OK",
  introductionButtonReady: "SONT PRONT BRO"
} as const
