import { CURRENCY_SYMBOL } from "$lib/modules/ui/constants"

export const nlBR = {
  address: "adresje",
  admin: "PATATBORD",
  adminInstruction: (price: number) => `ontgrendel onze nieuwste ratje-lekkere feature hè
    \nvoor ${price} ${CURRENCY_SYMBOL}. laat je custom trips maken\nvia een Bloomberg-stijl terminal voor
mentaal gestoorde stroopwafels ja toch. resultaten kunnen variëren ofzo.`,
  action: "Aktie",
  all: "allemaal hoor",
  activeProfit: "aktieve winst",
  adminUnlocked: "admin ontgrendeld lekker",
  adminUnlockedMessage: "Je hebt het Patatbord ontgrendeld snap je",
  ago: "geleden ofzo",
  alive: "levend hè",
  active: "aktief",
  activeTrips: "aktieve trips",
  allowance: "toestemming",
  approveAllowance: "goedkeuren max toestemming",
  approveAllowanceInstruction: "laat het contract uitgeven namens jou jongen",
  approvingAllowance: "goedkeuren toestemming",
  currentAllowance: "huidige toestemming",
  insufficientAllowance: "je hebt niet genoeg toestemming voor deze aktie hoor.",
  manageAllowance: "Beheer Toestemming",
  manageAllowanceDescription:
    "stel in hoeveel het game contract mag uitgeven namens jou. dit is verplicht om lol te hebben ja toch.",
  newAllowance: "NIEUWE TOESTEMMING",
  setAllowance: "Stel Toestemming In",
  settingAllowance: "Toestemming Instellen",
  authorFullTitle: "Moving Castles GmbH",
  totalValue: "totale waarde",
  totalValueExplanation:
    "de totale waarde van je ratje is de som van je gezondheid en PsychoDingen snap je",
  back: "terug hoor",
  balance: "Saldo",
  blockNumber: "BlokNummer",
  bottomMarqueeText: "ER ZIJN GEEN SLECHTE TRIPS, ALLEEN SLECHTE RATTEN HÈ.",
  buyRat: "Koop Ratje",
  buySomeTokens: `koop wat ${CURRENCY_SYMBOL}`,
  buyTokens: (amount: number): string => `koop ${amount} ${CURRENCY_SYMBOL} voor 0.001ETH`,
  cancel: "Afbreken",
  causeOfDeathShort: "DoD",
  confirm: "Bevestigen",
  confirmLiquidationMessage: (name: string): string =>
    `weet je zeker dat je wilt uitcashen hè? ${name} wordt afgemaakt in het proces ofzo.`,
  comeDown: "AFKOMEN JOH",
  connectBurner: "Verbind Burner",
  connectWallet: "Verbind wallet",
  connectedWallet: "Verbonden wallet",
  confirmLiquidateTripPrompt: (index: number): string =>
    `weet je zeker dat je trip #${index} wilt liquideren?`,
  cost: "Kosten:",
  createdTrip: "trip gemaakt",
  creatingTripIn: "trip maken in:",
  creationBlock: "Gemaakt @",
  creationCost: "Maak Kosten",
  createTrip: "Maak Trip",
  createTripButton: "maak trip",
  createTripPlaceholder: "je maakt een tripje ofzo...",
  creator: "maker",
  currentRat: "huidige ratje",
  debug: "Debug",
  deployed: "gedeployed lekker",
  destroyedTrip: "trip vernield",
  died: "DOODGEGAAN HÈ",
  dieFromTrip: "doodgaan van trip #",
  dieInTrip: "doodgaan in trip",
  diedTripping: "doodgegaan tijdens trippen #",
  disconnectWallet: "Verbreek wallet",
  egoDeathExplanation: `!!! ATTENTIE OPERATOR !!!\ntrips zijn ongeteste substanties en\nkunnen extreme dood veroorzaken bij je ratje hoor!`,
  empty: "leeg ofzo",
  enjoySkillfully: "GENIET MET SKILL JOH",
  events: "Gebeurtenissen",
  environment: "Omgeving",
  erc20Balance: "ERC20 Saldo",
  filter: "Filter",
  fomoAlertBalance: (balance: number): string => `FOMO ALARM! Saldo is ${balance} snap je`,
  forceRatLiquidation: "Forceer ratje liquidatie",
  getFreeTokens: (amount: number): string => `krijg ${amount} gratis ${CURRENCY_SYMBOL} lekker`,
  gettingRat: "Je ratje ophalen...",
  gettingTokens: "Tokens ophalen",
  getTokens: (amount: number): string => `krijg ${amount} $RAT`,
  graph: "Grafiek",
  hasTokens: "Heeft tokens",
  health: "GEZONDHEID",
  home: "Home",
  hot: "HEET OFZO",
  insufficientBalance: "Onvoldoende saldo hè",
  inventory: "Inventaris",
  issuingMemberCard: "Lidmaatschapskaart uitgeven",
  killInProgress: "AFMAKEN IN UITVOERING",
  kills: "Kills",
  lastVisit: "Laatste Bezoek",
  lastVisitedSecondsAgo: (seconds: number): string => `Laatst bezocht ${seconds} seconden geleden`,
  let: "laat",
  liquidate: "Liquideren",
  liquidated: "geliquideerd",
  liquidatingTrip: "Trip liquideren",
  log: "Log",
  liquidateRatButtonText: "CA$H UIT",
  liquidateRatInstruction: "cash uit de totale waarde van je ratje, voor een kleine fee snap je",
  liquidationBlockShort: "Liq. @",
  liquidationValueShort: "Liq. Waarde",
  loadingMsg: "LaadMsg",
  loadingPercentage: "Laden%",
  locked: "vergrendeld",
  masterKey: "Patatbord ontgrendeld",
  maxReward: "MAX UITBETALING",
  maxValuePerWin: "MAX UITBETALING",
  maxValuePerWinLabel: "MAX WAARDE PER WIN",
  messageCannotBeEmpty: "bericht kan niet leeg zijn hoor",
  minRatValueToEnter: "min ratje waarde om binnen te komen",
  music: "Muziek",
  musicOn: "Muziek: AAN",
  musicOff: "Muziek: UIT",
  minRatValueToTrip: "MIN RATJE WAARDE OM TE TRIPPEN",
  minRatValueWarning: (value: number): string => `ratje waarde te laag (minimaal ${value})`,
  moveOn: "VERDER GAAN HÈ",
  name: "Naam",
  nameCannotBeEmpty: "naam kan niet leeg zijn",
  nameTooLong: "naam is te lang (maximaal 50 karakters)",
  newIndication: "Is nieuw",
  invested: "Geïnvesteerd",
  noLogs: "GEEN LOGS",
  noRatWarning: "Koop een ratje om deze trip te betreden ja toch",
  noData: "Kweenie",
  now: "nu",
  onChainBalance: "On-chain Saldo",
  online: "online",
  owner: "Eigenaar",
  pastRatsCount: "Vorige Ratjes",
  payout: "Uitbetaling",
  player: "Speler",
  playerId: "SPELER ID:",
  psychoInventory: "PsychoDingen",
  past: "Verleden",
  pastTrips: "Vorige trips",
  profit: "Winst",
  portfolio: "Portfolio",
  psychoObjectExplanation:
    "PsychoDingen zijn materialisaties van mentale items verkregen tijdens trippen. Niemand weet echt hoe ze werken, maar ze zijn 1000% echt, absoluut GEEN hallucinaties snap je",
  rat: "Ratje",
  ratAmountKilled: "Ratjes gedood",
  ratBeingRevived:
    "RATJE WORDT HERLEVEN UIT DIEPE DRUG-GEÏNDUCEERDE COMA.\nALLES IS NORMAAL HÈ.\nEVEN GEDULD AUB...",
  ratCreationTimeout: "Timeout wachten op ratje creatie",
  ratHallucinatoryState: "RATJE NOG IN HALLUCINATOIRE STAAT.\nEVEN GEDULD AUB...",
  ratId: "RATJE ID:",
  rats: "Ratjes",
  ratValue: (name: string) => name + "'s totale waarde",
  readyQuestion: "Klaar ofzo?",
  requestTokens: "Vraag tokens aan van het contract",
  revokeApproval: "Intrekken goedkeuring",
  revokeApprovalInstruction: "Trek contract goedkeuring in (zet op 0)",
  riskHi: "HOOG",
  riskLow: "LAAG",
  riskMid: "MIDDEL",
  riskNightmare: "NACHTMERRIE HÈ",
  riskProfile: "Risicoprofiel:",
  riskUnclear: "ONDUIDELIJK",
  selectCategoryPrompt: "Selecteer een categorie voor je trip snap je",
  selectFolder: "Selecteer trip categorie",
  send: "Versturen",
  sendRatToTrip: "TRIPPEN",
  sent: "verstuurd",
  showDepletedTrips: "toon uitgeputte trips",
  sign: "TEKENEN",
  siteTitle: "RAT.FUN",
  sortByBalance: "sorteer op saldo",
  sortByKillCount: "sorteer op kill aantal",
  sortByPopularity: "sorteer op populariteit",
  sortByVisit: "sorteer op bezoek",
  sortChronologically: "sorteer chronologisch",
  spawn: "Spawnen",
  spawned: "Gespawned",
  stop: "Stop",
  supervisorModeActivated: "Supervisor modus geactiveerd",
  survived: "OVERLEEFD LEKKER",
  thereAreTrips: (count: number): string => `Er zijn ${count} trips hoor`,
  tokens: "Tokens",
  tokensAvailable: "Dit zijn beschikbare tokens in je wallet",
  toTrip: "naar trip #",
  toTripShort: "naar trip",
  topBarMarqueeText:
    "ER IS GEEN GELUK. ALLEEN SKILL. ER ZIJN GEEN SLECHTE TRIPS, ALLEEN SLECHTE RATJES JA TOCH.",
  topMarqueeText: "RAT.FUN IS EEN SPEL VAN SKILL SNAP JE.",
  transactionInProgress: "Transactie bezig...",
  traumwertSteuer: "TraumwertSteuer",
  traumwertSteuerExplanation: (percentage: number): string => `${percentage}% bedrijfsbelasting`,
  trip: "Trip",
  tripBalance: "Trip saldo",
  tripCreationCostLabel: "Trip creatie investering",
  tripDescription: "Verwachte symptomen",
  tripGotDepleted: (index: number): string => `Trip #${index} is uitgeput geraakt hè`,
  tripLogs: "TRIP LOGS",
  tripPrompt: "TRIP PROMPT:",
  tripReport: "TRIP RAPPORT",
  trips: "Trips",
  tripsLabel: "Trips:",
  tripSitters: "TRIP SITTERS",
  unlockAdmin: "Ontgrendel Admin",
  unlockAdminInstruction: "Ontgrendel Patatbord",
  unlockingAdmin: "Admin Ontgrendelen",
  unlock: "Ontgrendelen",
  unknown: "onbekend ofzo",
  valueLabel: "WAARDE",
  visits: "Bezoeken",
  waitForTokens: "🫵JIJ🫵 hebt geen $RAT tokens hoor. 🫵JIJ🫵 komt later terug snap je.",
  waitBlocks: (blocks: number): string => `Wacht ${blocks} blokken`,
  walletType: "Wallet Type",
  worldAddress: "Wereld adres",
  you: "Jij",
  youAreSet: (name: string): string => `${name}, je bent klaar jongen!`,
  youCreatedTrip: (index: number): string => `Je hebt trip #${index} gemaakt lekker`,
  youIndication: (name: string) => `Dit ben jij hè: ${name}`,
  youLiquidatedTrip: (index: number): string => `Je hebt trip #${index} geliquideerd`,
  yourName: "JOUW NAAM",
  youWillRecover: "Je zult herstellen ofzo",
  allIsFine: "ALLES IS PRIMA HÈ.\n EVENTJES GEDULD JOH.\n WE WAARDEREN JE GEDULD.",
  tripHeader: "Selecteer een categorie",
  tripHeaderNoRat: "Koop ratje om trip te selecteren.",
  unlockAdminHeader: "Ontgrendel Patatbord",
  unlockAdminMessage:
    "Laat je custom trips maken via een Bloomberg-stijl terminal voor de mentaal gestoorden. Resultaten kunnen variëren snap je.",
  // Trip processing popup messages
  tripProcessingFirst: "ALLES IS PRIMA HÈ.\n EVENTJES GEDULD JOH.\n WE WAARDEREN JE GEDULD.",
  tripProcessingSecond: "RATJE NOG IN HALLUCINATOIRE STAAT.\nEVEN GEDULD AUB...",
  tripProcessingThird: "RATJE WORDT HERLEVEN UIT DIEPE DRUG-GEÏNDUCEERDE COMA...",
  // Trip setup messages
  tripSetupPresents: "*** RAT.FUN WETENSCHAPPELIJKE INSTRUMENTEN BV PRESENTEERT ***",
  tripSetupWarning: "WAARSCHUWING JOH",
  tripSetupExperimental: "DIT IS EEN EXPERIMENTELE ERVARING EN KAN DODELIJK ZIJN HÈ",
  tripSetupLiability: "ABSOLUUT GEEN AANSPRAKELIJKHEID VOOR PSYCHOLOGISCHE VERMINKING",
  tripSetupWarranty:
    "GARANTIE NIETIG. GELDT VOOR DE SPELER, RATJE SUBJECT EN ELKE ANDERE ENTITEIT IN DE WERELD SNAP JE.",
  tripSetupResponsibility:
    "DOOR DEZE MACHINE NIET TE VERNIETIGEN ACCEPTEER JE VOLLEDIGE VERANTWOORDELIJKHEID",
  tripSetupFault: "ALLES IS JOUW SCHULD OFZO",
  tripSetupSkull: "ALLE GEBEURTENISSEN VINDEN PLAATS IN DE SCHEDEL VAN HET RATJE",
  tripSetupSetting: "Trip instellen: ",
  tripSetupPneumatic: "= Pneumatisch systeem geactiveerd",
  tripSetupConveyed: "= Ratje vervoerd naar trip kamer",
  tripSetupDiaper: "= PETA goedgekeurde luier bevestigd",
  tripSetupProbes: "= Intracraniale sondes bevestigd",
  tripSetupDosed: "= Ratje gedoseerd met 44mg Slopamine",
  tripSetupInitiated: "= Trip gestart: ",
  // Trip report
  tripReportStart: "TRIP RAPPORT // START",
  tripReportEnd: "TRIP RAPPORT // EINDE",
  balanceLabel: "Saldo",
  dead: "DOOD HÈ",
  // Spawn error messages
  somethingWentWrong: "Er ging iets fout ofzo",
  errorOccurred: "Er is een fout opgetreden tijdens het spawn proces. Probeer opnieuw hoor.",
  startOver: "Opnieuw beginnen",
  // Session setup
  sessionSetup: "Sessie Instellen",
  sessionSetupDescription:
    "Maak een veilige sessie om met het spel te interacteren zonder elke transactie te tekenen ja toch.",
  setupSession: "Sessie instellen",
  // Online users
  onlinePlayers: "Online spelers",
  connecting: "Verbinden...",
  onlinePlayersCount: (count: number): string => `Online Spelers (${count})`,
  noPlayersOnline: "Geen spelers online",
  // Settings
  playerNotifications: "Speler Notificaties",
  tripNotifications: "Trip Notificaties",
  language: "Taal",
  // Loading sequence
  loadingCompany: "RAT.FUN WETENSCHAPPELIJKE INSTRUMENTEN BV",
  loadingCopyright: "(c) 2034 Sexc-hell island, Kowloon, Hong Kong",
  loadingRights: "Alle rechten voorbehouden in overeenstemming met Maritiem Recht",
  loadingDissociated: "VOLLEDIG GEDISSOCIEERD EN ONTEIGEND ZUSTERBEDRIJF VAN MOVING CASTLES GMBH",
  loadingPatent: "Patent in behandeling in alle niet-aangesloten gebieden",
  loadingTrademarks:
    "FUN en RAT zijn geregistreerde handelsmerken van RAT.FUN WETENSCHAPPELIJKE INSTRUMENTEN BV",
  loadingAgreement:
    "DOOR DEZE TEKST TE LEZEN GA JE AKKOORD MET DE VOORWAARDEN VAN DE OVEREENKOMST EN DOE JE AFSTAND VAN JE MENSENRECHTEN HÈ",
  loadingBoot: "SLOP MACHINE OPSTARTEN...",
  // Introduction messages
  introductionStep1: "Goooooeieeeeee mooooorgen **OPERATOR** hè!",
  introductionStep2:
    "welkom bij onze ratje-gecontroleerde remote viewing **SLOP MACHINE** snap je.",
  introductionStep3: "als je 'm vakkundig bedient brengt deze machine je grote rijkdom ja toch!",
  introductionStep4:
    "pomp je ratjes vol met drugs en stuur ze trippend op pad, cash dan tokens uit door hun succes te exploiteren ofzo.",
  introductionStep5: "ik voel je dopamine injectors tintelen! waar wacht je op jongen?",
  introductionButtonOk: "OKÉ HÈ",
  introductionButtonReady: "IK BEN KLAAR LEKKER"
} as const
