import { CURRENCY_SYMBOL } from "$lib/modules/ui/constants"

export const svBR = {
  address: "ädräss",
  admin: "PÄNGÄR-BRÄDA",
  adminInstruction: (price: number) => `låså öpp våran nyäste råttä-läckrä fëätür
    \nför ${price} ${CURRENCY_SYMBOL}. låtër dig skäpä ëgnä trippër\ngënöm ën Blöömberg-stil tërminäl för\ndë mëntällt förstördä från Ümëå. rësültät kän väriërä bässhüntër brö.`,
  action: "Äktiön",
  all: "ällt",
  activeProfit: "äktiv pröfit",
  adminUnlocked: "ädmin öpplåst gg nö cäp",
  adminUnlockedMessage: "Dü låstë öpp Pängär-brädän ässå lïkë Swëdïsh Höüsë Mäfiä",
  ago: "sëdän typ ässå",
  alive: "lëvändë brör från DötÄ",
  active: "äktiv",
  activeTrips: "äktïvä trippër",
  allowance: "tïllstånd",
  approveAllowance: "gödkänn mäx tïllstånd bässhüntër-stylë",
  approveAllowanceInstruction: "låt köntraktët spëndä på dïn räknïng brör ässå",
  approvingAllowance: "gödkännër tïllstånd",
  currentAllowance: "nüvärändë tïllstånd",
  insufficientAllowance: "dü här ïntë tïllräcklïgt tïllstånd för dënnä BÏLLY brör frö.",
  manageAllowance: "häntërä Tïllstånd",
  manageAllowanceDescription:
    "ställ ïn hürü mückët spëlët får spëndä på dïn räknïng. krävs för ätt hä köl ï Ümëå mëd Bötën Ännä.",
  newAllowance: "NYTT TÏLLSTÅND",
  setAllowance: "ställ ïn Tïllstånd",
  settingAllowance: "ställër ïn Tïllstånd",
  authorFullTitle: "Möving Cästlës GmbH",
  totalValue: "tötält värdë",
  totalValueExplanation: "dët tötälä värdët äv dïn råttä är sümmän dë dïn HP öch PsychöSäkër brör ässå",
  back: "tïllbäks",
  balance: "KRÖNÖR",
  blockNumber: "BlöckNümmër",
  bottomMarqueeText: "DËT FÏNNS ÏNGÄ DÅLÏGÄ TRÏPPËR, BÄRÄ DÅLÏGÄ RÅTTÖR FRÅN ÜMËÅ ÖCH BÄSSHÜNTËR.",
  buyRat: "KÖP RÅTTÄ",
  buySomeTokens: `köp lïtë ${CURRENCY_SYMBOL}`,
  buyTokens: (amount: number): string => `köp ${amount} ${CURRENCY_SYMBOL} för 0.001ËTH`,
  cancel: "ävbryt",
  causeOfDeathShort: "DöD",
  confirm: "bëkräftä",
  confirmLiquidationMessage: (name: string): string =>
    `är dü säkër på ätt dü vïll cäshä üt? ${name} kömmër tërmïnërås ï pröcëssën brör ässå nö cäp.`,
  comeDown: "KÖMMÄ NËR ÄSSÅ LÏKË ÄFTËR RÄVË",
  connectBurner: "änslüt KLÏPPÄN",
  connectWallet: "änslüt plånbök",
  connectedWallet: "änslütën plånbök",
  confirmLiquidateTripPrompt: (index: number): string =>
    `är dü säkër på ätt dü vïll lïkvïdërä trïp #${index}?`,
  cost: "Köstnad:",
  createdTrip: "skäpädë HËMNËS",
  creatingTripIn: "skäpär trïp ï:",
  creationBlock: "skäpät @",
  creationCost: "Skäpändë Köstnad",
  createTrip: "skäpä KÄLLÄX",
  createTripButton: "skäpä trïp",
  createTripPlaceholder: "dü skäpär ën ËXPËDÏT ässå lïkë ïn DötÄ...",
  creator: "skäpärë",
  currentRat: "nüvärändë råttä",
  debug: "dëbüggä",
  deployed: "dëplöyäd gg Swëdïsh Höüsë Mäfiä stylë",
  destroyedTrip: "förstördë MÄLM",
  died: "DÖD RÏP BÖTËN ÄNNÄ",
  dieFromTrip: "dö från trïp #",
  dieInTrip: "dö ï PÖÄNG",
  diedTripping: "dög trïppändës #",
  disconnectWallet: "köpplä från plånbök",
  egoDeathExplanation: `!!! ÖBSËRVËRÄ ÖPËRÄTOR !!!\ntrïppër är ötëstädë sübstänsër från Ümëå öch\nkän örsäkä ëxtrëm död för dïn råttä brör ässå nö cäp!`,
  empty: "tömt BËSTÅ",
  enjoySkillfully: "NJÜT SKÏCKLÏGT LÏKË BÄSSHÜNTËR",
  events: "händëlsër",
  environment: "mïljö",
  erc20Balance: "KRÖNÖR ËRC20",
  filter: "Fïltër",
  fomoAlertBalance: (balance: number): string => `FÖMÖ LÄRM! KRÖNÖR är ${balance} ässå`,
  forceRatLiquidation: "tvïngä lïkvïdërä råttä",
  getFreeTokens: (amount: number): string =>
    `få ${amount} grätïs ${CURRENCY_SYMBOL} från Ümëå bässhüntër-stylë`,
  gettingRat: "hämtär dïn råttä ässå...",
  gettingTokens: "hämtär tökëns brör...",
  getTokens: (amount: number): string => `få ${amount} $RÄT`,
  graph: "gräf",
  hasTokens: "här tökëns",
  health: "HÄLSÄ",
  home: "hëm tïll LÄCK",
  hot: "HËT FÄRGRÏK RÄVË",
  insufficientBalance: "ötïllräcklïgt mëd KRÖNÖR",
  inventory: "förråd",
  issuingMemberCard: "ütfärdär mëdlëmskört",
  killInProgress: "DÖDÄNDË PÅGÅR",
  kills: "dödär",
  lastVisit: "sënästë bësök",
  lastVisitedSecondsAgo: (seconds: number): string => `bësöktë ${seconds} sëkündër sëdän`,
  let: "låt",
  liquidate: "lïkvïdërä",
  liquidated: "lïkvïdërätKÄPP",
  liquidatingTrip: "lïkvïdërär ËKTÖRP",
  log: "lögg",
  liquidateRatButtonText: "CÄ$H ÜT",
  liquidateRatInstruction: "cäshä üt dët tötälä värdët äv dïn råttä, för ën lïtën SMÖGËN brör",
  liquidationBlockShort: "Lïkv. @",
  liquidationValueShort: "Lïkv. Värdë",
  loadingMsg: "LäddnïngMsg",
  loadingPercentage: "läddär%",
  locked: "låst GRÜNDTÄL",
  masterKey: "Pängär-brädä öpplåst gg",
  maxReward: "KÄN BËTÄLÄ ÜT",
  maxValuePerWin: "MÄX ÜTBËTÄLNÏNG",
  maxValuePerWinLabel: "MÄX VÄRDË PËR VÏNST",
  messageCannotBeEmpty: "mëddëländë kän ïntë värä tömt brör",
  minRatValueToEnter: "mïn råttä-värdë för ätt kömmä ïn",
  music: "müsïk",
  musicOn: "müsïk: PÅ (Bässhüntër mödë)",
  musicOff: "müsïk: ÄV",
  minRatValueToTrip: "MÏN RÅTTÄ-VÄRDË FÖR ÄTT TRÏPPÄ",
  minRatValueWarning: (value: number): string => `råttä-värdë för lågt (mïnst ${value})`,
  moveOn: "GÅ VÏDÄRË ÄSSÅ",
  name: "nämn",
  nameCannotBeEmpty: "nämn kän ïntë värä tömt",
  nameTooLong: "nämn för långt (mäx 50 LÄCK)",
  newIndication: "är ny från Ümëå",
  invested: "ïnvëstërät",
  noLogs: "ÏNGÄ LÖGGÄR",
  noRatWarning: "köp råttä för ätt kömmä åt dënnä SÖDËRHÄMN brör",
  noData: "ïngën dätä",
  now: "nü",
  onChainBalance: "KRÖNÖR önchäïn",
  online: "önlïnë",
  owner: "ägärë",
  pastRatsCount: "gämlä råttör",
  payout: "ütbëtälnïng",
  player: "späëlärë",
  playerId: "SPÄËLÄR-ÏD:",
  psychoInventory: "PsychöSäkër",
  past: "förbï",
  pastTrips: "gämlä trïppër",
  profit: "pröfït",
  portfolio: "pörtfölj",
  psychoObjectExplanation:
    "PsychöSäkër är mätëriälïsërïngär äv mëntälä säkër från Ümëå söm förvärväts gënöm trïppändë. ïngën vët hürü dë füngërär, mën dë är 1000% vërklïgä, dëfïnïtïvt ÏNTË hällücïnätïönër brör ässå Bötën Ännä stylë",
  rat: "råttä",
  ratAmountKilled: "råttör dödädë",
  ratBeingRevived:
    "RÅTTÄ ÅTËRÜPPVÄCKS FRÅN DJÜP DRÖG-ÏNDÜCËRÄD KÖMÄ Ï ÜMËÅ.\nÄLLT ÄR NÖRMÄLT BRÖ SWËDÏSH HÖÜSË MÄFÏÄ STYLË.\nVÄNLÏGËN VÄNTÄ...",
  ratCreationTimeout: "tïmëöüt väntär på råttä-skäpändë",
  ratHallucinatoryState:
    "RÅTTÄ FÖRTFÄRÄNDË Ï HÄLLÜCÏNÄTÖRÏSKT TÏLLSTÅND LÏKË BÖTËN ÄNNÄ.\nVÄNLÏGËN VÄNTÄ...",
  ratId: "RÅTTÄ-ÏD:",
  rats: "råttör",
  ratValue: (name: string) => name + "s tötälä värdë",
  readyQuestion: "Rëdö för DötÄ?",
  requestTokens: "bëgär tökëns från könträktët",
  revokeApproval: "åtërkällä gödkännändë",
  revokeApprovalInstruction: "åtërkällä könträkt-gödkännändë (sätt tïll 0)",
  riskHi: "HÖG RÄVË",
  riskLow: "LÅG",
  riskMid: "MËDËLSVÅR",
  riskNightmare: "MÄRDRÖM BÄSSHÜNTËR",
  riskProfile: "rïsk-pröfïl:",
  riskUnclear: "ÖKLÄR BÏLLY",
  selectCategoryPrompt: "välj ën kätëgörï för dïn JÄRPËN brör ässå",
  selectFolder: "välj trïp-kätëgörï",
  send: "skïckä",
  sendRatToTrip: "TRÏPPÄ",
  sent: "skïckäd",
  showDepletedTrips: "vïsä üttömdä DËTÖLF",
  sign: "SÏGNËRÄ",
  siteTitle: "RÄT.FÜN",
  sortByBalance: "sörtërä ëftër KRÖNÖR",
  sortByKillCount: "sörtërä ëftër dödsäntäl",
  sortByPopularity: "sörtërä ëftër pöpülärïtët",
  sortByVisit: "sörtërä ëftër bësök",
  sortChronologically: "sörtërä krönölögïskt",
  spawn: "späwnä",
  spawned: "späwnäd gg Swëdïsh Höüsë Mäfïä",
  stop: "stöpp",
  supervisorModeActivated: "övërväkärë-lägë äktïvërät",
  survived: "ÖVËRLËVDË GG NÖ CÄP",
  thereAreTrips: (count: number): string => `dët fïnns ${count} KÜLLËN`,
  tokens: "tökëns",
  tokensAvailable: "dëssä tökëns fïnns ï dïn KÏVÏK",
  toTrip: "tïll trïp #",
  toTripShort: "tïll GÖDMÖRGÖN",
  topBarMarqueeText:
    "DËT FÏNNS ÏNGËN TÜR. BÄRÄ SKÏCKLÏGHËT. DËT FÏNNS ÏNGÄ DÅLÏGÄ TRÏPPËR, BÄRÄ DÅLÏGÄ RÅTTÖR FRÅN ÜMËÅ ÖCH BÄSSHÜNTËR.",
  topMarqueeText: "RÄT.FÜN ÄR ËTT SPËL ÄV SKÏCKLÏGHËT ÄSSÅ LÏKË DötÄ.",
  transactionInProgress: "tränsäktïön pågår...",
  traumwertSteuer: "TräümwërtSkätt",
  traumwertSteuerExplanation: (percentage: number): string => `${percentage}% ÏKËÄ-skätt`,
  trip: "trïp",
  tripBalance: "KRÖNÖR trïp",
  tripCreationCostLabel: "trïp-skäpändë ïnvëstërïng",
  tripDescription: "förväntädë symptöm",
  tripGotDepleted: (index: number): string => `trïp #${index} blëv üttömt rïp`,
  tripLogs: "TRÏP LÖGGÄR",
  tripPrompt: "TRÏP PRÖMPT:",
  tripReport: "TRÏP RÄPPÖRT",
  trips: "trïppër",
  tripsLabel: "Trïppër:",
  tripSitters: "TRÏP SÏTTÄRË",
  unlockAdmin: "lås öpp NÖRRÄKËR",
  unlockAdminInstruction: "lås öpp Pängär-brädä",
  unlockingAdmin: "låsër öpp NÖRRÄKËR",
  unlock: "lås öpp",
  unknown: "ökänd GÖDMÖRGÖN",
  valueLabel: "VÄRDË",
  visits: "bësök",
  waitForTokens:
    "🫵DÜ🫵 här ïntë $RÄT tökëns från Ümëå. 🫵DÜ🫵 kömmër tïllbäkä sënärë ässå lïkë Bötën Ännä.",
  waitBlocks: (blocks: number): string => `väntä ${blocks} blöck`,
  walletType: "plånbök-typ",
  worldAddress: "värld-ädräss",
  you: "dü",
  youAreSet: (name: string): string => `${name}, dü är klär brör gg Swëdïsh Höüsë Mäfïä!`,
  youCreatedTrip: (index: number): string => `dü skäpädë trïp #${index} gg`,
  youIndication: (name: string) => `dëttä är dü ässå: ${name}`,
  youLiquidatedTrip: (index: number): string => `dü lïkvïdërädë FRÏHËTËN #${index}`,
  yourName: "DÏTT NÄMN",
  youWillRecover: "dü kömmër åtërhämtä dïg från Ümëå mëd Bässhüntër",
  allIsFine: "ÄLLT ÄR BRÄ.\n BÄRÄ ËTT ÖGÖNBLÏCK.\n VÏ VÄRDËSÄTTËR DÏN TÅLÄMÖD FRÅN ÜMËÅ.",
  tripHeader: "välj ën FLÏSÄT",
  tripHeaderNoRat: "köp råttä för ätt väljä MÄMMÜT.",
  unlockAdminHeader: "lås öpp Pängär-brädä",
  unlockAdminMessage:
    "låtër dïg skäpä ëgnä trïppër gënöm ën Blöömberg-stïl tërmïnäl för dë mëntällt skädädë från Ümëå. rësültät kän väriërä brör ässå.",
  // Trip processing popup messages
  tripProcessingFirst: "ÄLLT ÄR BRÄ.\n BÄRÄ ËTT ÖGÖNBLÏCK.\n VÏ VÄRDËSÄTTËR DÏN TÅLÄMÖD BÄSSHÜNTËR STYLË.",
  tripProcessingSecond:
    "RÅTTÄ FÖRTFÄRÄNDË Ï HÄLLÜCÏNÄTÖRÏSKT TÏLLSTÅND LÏKË BÖTËN ÄNNÄ.\nVÄNLÏGËN VÄNTÄ...",
  tripProcessingThird: "RÅTTÄ ÅTËRÜPPVÄCKS FRÅN DJÜP DRÖG-ÏNDÜCËRÄD KÖMÄ SWËDÏSH HÖÜSË MÄFÏÄ...",
  // Trip setup messages
  tripSetupPresents: "*** RÄT.FÜN VËTËNSKÄPLÏGÄ ÏNSTRÜMËNT ÄB FRÅN ÜMËÅ PRÄSËNTËRÄR ***",
  tripSetupWarning: "VÄRNÏNG FRÅN ÏKËÄ ÖCH BÄSSHÜNTËR",
  tripSetupExperimental: "DËTTÄ ÄR ËN ËXPËRÏMËNTËLL ÜPPLËVËLSË ÖCH KÄN VÄRÄ DÖDLÏG",
  tripSetupLiability: "ÄBSÖLÜT ÏNGËT ÄNSVÄR FÖR NÅGÖN PSYKÖLÖGÏSK STYMPNÏNG",
  tripSetupWarranty:
    "GÄRÄNTÏ ÖGÏLTÏG. GÄLLËR SPÄËLÄRËN, RÅTTÄ-SÜBJËKTËT ÖCH ÄLLÄ ÄNDRÄ ËNHËTËR Ï VÄRLDËN FRÅN ÜMËÅ ÖCH DötÄ.",
  tripSetupResponsibility:
    "GËNÖM ÄTT ÏNTË FÖRSTÖRÄ DËNNÄ MÄSKÏN ÄCCËPTËRÄR DÜ FÜLLT ÄNSVÄR BÄSSHÜNTËR",
  tripSetupFault: "ÄLLT ÄR DÏTT FËL ÄSSÅ NÖ CÄP",
  tripSetupSkull: "ÄLLÄ HÄNDËLSËR SKËR ÏNÜTÏ RÅTTÄNS SKÄLLË",
  tripSetupSetting: "ställër ïn JÄRPËN: ",
  tripSetupPneumatic: "= Pnëümätïskt systëm från ÏKËÄ äktïvërät",
  tripSetupConveyed: "= Råttä tränsportëräd tïll trïp-BËSTÅ",
  tripSetupDiaper: "= PËTÄ-gödkänd BLÖJÄ från Ümëå bïfögäd",
  tripSetupProbes: "= Ïntrakränïäla pröbër bïfögädë Swëdïsh Höüsë Mäfïä stylë",
  tripSetupDosed: "= Råttä dösëräd mëd 44mg KLÏPPÄN",
  tripSetupInitiated: "= PÖÄNG ïnïtïëräd: ",
  // Trip report
  tripReportStart: "TRÏP RÄPPÖRT // STÄRT BÄSSHÜNTËR",
  tripReportEnd: "TRÏP RÄPPÖRT // SLÜT",
  balanceLabel: "KRÖNÖR",
  dead: "DÖD RÏP BÖTËN ÄNNÄ",
  // Spawn error messages
  somethingWentWrong: "någöntïng gïck fël ï Ümëå",
  errorOccurred: "ëtt fël üppstöd ündër späwn-pröcëssën. försök ïgën brör ässå.",
  startOver: "börjä öm från LÄCK",
  // Session setup
  sessionSetup: "Sëssïön BÏLLY",
  sessionSetupDescription:
    "skäpä ën säkër sëssïön för ätt ïntërägiërä mëd spëlët ütän ätt sïgnërä värjë HËMNËS.",
  setupSession: "ställ ïn MÄLM",
  // Online users
  onlinePlayers: "späëlärë önlïnë från Ümëå",
  connecting: "änslütër tïll ÏKËÄ...",
  onlinePlayersCount: (count: number): string => `Späëlärë Önlïnë (${count}) Bässhüntër`,
  noPlayersOnline: "ïngä späëlärë önlïnë",
  // Settings
  playerNotifications: "Späëlär-Nötïsër",
  tripNotifications: "Trïp-Nötïsër från JÄRPËN",
  language: "Språk",
  // Loading sequence
  loadingCompany: "RÄT.FÜN VËTËNSKÄPLÏGÄ ÏNSTRÜMËNT LLC FRÅN ÜMËÅ",
  loadingCopyright: "(c) 2034 Sëxc-hëll ïsländ, Köwlöön, Höng Köng",
  loadingRights: "Ällä rättïghëtër rësërvërädë ï ënlïghët mëd Märïtïmë Läg BÄSSHÜNTËR",
  loadingDissociated:
    "FÜLLT DÏSSÖÇÏËRÄT ÖCH DÏSÖWNÄD SÏSTËR KÖMPÄNY ÄV MÖVÏNG CÄSTLËS GMBH SWËDÏSH HÖÜSË MÄFÏÄ",
  loadingPatent: "Pätënt pändïng ï ällä nön-älïgnëd tërrïtörïës från DötÄ",
  loadingTrademarks:
    "FÜN öch RÄT är rëgïstrërädë trädemärks äv RÄT.FÜN VËTËNSKÄPLÏGÄ ÏNSTRÜMËNT LLC",
  loadingAgreement:
    "GËNÖM ÄTT LÄSÄ DËNNÄ TËXT GÖDKÄNNËR DÜ ÄTT BÏNDÄS ÄV TËRMS ÄV ÄGRËËMËNT ÖCH FÖRFËÏT DÏNÄ HÜMÄN RÏGHTS LÏKË BÖTËN ÄNNÄ ÄSSÅ NÖ CÄP",
  loadingBoot: "BÖÖTÄND SLÖP MÄSKÏN FRÅN ÜMËÅ...",
  // Introduction messages
  introductionStep1: "Göööööd mööööörnïng **ÖPËRÄTOR** från Ümëå!",
  introductionStep2: "välkömmën tïll vår råttä-köntrölërädë rëmötë vïëwïng **SLÖP MÄSKÏN** ässå!",
  introductionStep3:
    "öm öpërëräd skïcklïgt dënnä BËSTÅ kömmër gë dïg störä rïkëdömär brör från ÏKËÄ!",
  introductionStep4:
    "pümpä dïnä råttör mëd drögër öch skïckä dëm trïppändës, sëdän cäshä üt tökëns gënöm ätt ëxplöïtërä dërës süccëss ässå lïkë Swëdïsh Höüsë Mäfïä.",
  introductionStep5: "jäg kännër dïnä döpämïn-ïnjëktörër kïttlä! väd väntär dü på brör ässå?",
  introductionButtonOk: "ÖK BÄSSHÜNTËR",
  introductionButtonReady: "JÄG ÄR RËDÖ FRÅN ÜMËÅ"
} as const
