export const PROMPTS = [
    "trypophobia",
    "staring",
    "laughing",
    "sad",
    "maniac",
    "crazy",
    "sunlit",
    "crying",
    "insane",
    "happy",
    "beefy",
    "encrypted",
    "vulgar",
    "divine",
    "evil",
    "mistaken",
    "labyrinthine",
    "decrepid",
    "wasted",
    "wasteland",
    "abandoned",
    "scammy",
    "wide-eyed",
    "redacted",
    "censored",
    "soiled",
    "human-faced",
    "rat-faced",
    "rat-brained",
    "lab-rat",
    "perverted",
    "pervy",
    "blazing",
    "blazing fast",
    "corrupted",
    "dadaist",
    "absurd",
    "bad",
    "intense",
    "angelic",
    "radiant",
    "gabber",
    "smiling",
    "flooded",
    "burning",
    "xeroxed",
    "melted",
    "disfigured",
    "bug eyed",
    "cursed",
    "cursed",
    "strobed",
    "crunchy",
    "hyper-accelerated",
    "euphoric",
    "exstatic",
    "trance",
    "crusty",
    "tear-eyed",
    "chunky",
    "terry gilliam",
    "gorepunk",
    "screaming",
    "surprised",
    "singing",
    "tortured",
    "yelling",
    "gore",
    "cut-up",
    "howling",
    "pig-nosed",
    "rat-faced",
    "ratty",
    "rotting",
    "humiliated",
    "broken",
    "lookmaxed",
    "merrymaxed",
    "life-maxed",
    "sublime",
    "sneering",
    "sparkling",
    "dark",
    "sickly sweet",
    "alien",
    "vivisection",
    "messy",
    "fairytale",
    "alien faced",
    "embarrased",
    "peaceful",
    "viral",
    "acid",
    "infected",
    "massacre",
    "gore-spattered",
    "acid fried",
    "smeared",
    "fecal stained",
    "film grain",
    "trashed",
    "aged",
    "decayed",
    "rotting",
    "stained",
    "graffiti",
    "goya",
    "junji ito",
    "allan moore",
    "walt disney",
    "slimepunk",
    "highly detailed",
    "masterwork",
    "extreme texture",
    "macroshot",
    "spray paint",
    "scarred",
    "collage",
    "punk collage",
    "dead kennedys",
    "death metal",
    "john heartfield",
    "mutant",
    "freak",
    "gimp suit",
    "Giovanni Battista Piranesi",
    "scarred",
    "collage",
    "otto dix",
    "francis bacon",
    "george grosz",
    "drawing",
    "plotter",
    "trash",
    "lo-res",
    "xeroxed",
    "punk zine",
    "deep fried",
    "research chemical",
    "fried",
    "finger painting",
    "digipunk",
    "scrollpunk",
    "john bauer",
    "h.r. giger",
    "4K",
    "griftpunk",
    "tagged",
    "financepunk",
    "corecore",
    "extremely detailed",
    "crust-punk",
    "cursed",
    "fisheye",
    "flamed",
    "joseph beuys",
    "cut-up",
    "metalcore",
    "metallic",
    "crustcore",
    "crust",
    "naive",
    "splatter",
    "air-brushed",
    "black metal",
    "crt",
    "air-brushed",
    "distorted",
    "scanned",
    "inverted",
    "scan",
    "scanlines",
    "crusted",
    "brothers grimm",
    "pain",
    "grimm",
    "sprayed",
    "high contrast",
    "black and white",
    "monochrome",
    "go pro",
    "gorechunk",
    "VHS distorted",
    "betamax",
    "trypophobia"
  ]