// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { DevSystem } from "../../systems/DevSystem.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { WorldContextConsumerLib } from "@latticexyz/world/src/WorldContext.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type DevSystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "ratfun", name: "DevSystem" }))
DevSystemType constant devSystem = DevSystemType.wrap(
  0x737972617466756e000000000000000044657653797374656d00000000000000
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title DevSystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library DevSystemLib {
  error DevSystemLib_CallingFromRootSystem();

  function giveCallerTokens(DevSystemType self) internal {
    return CallWrapper(self.toResourceId(), address(0)).giveCallerTokens();
  }

  function giveCallerTokens(CallWrapper memory self) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert DevSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_giveCallerTokens.giveCallerTokens, ());
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function giveCallerTokens(RootCallWrapper memory self) internal {
    bytes memory systemCall = abi.encodeCall(_giveCallerTokens.giveCallerTokens, ());
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function callFrom(DevSystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(DevSystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), WorldContextConsumerLib._msgSender());
  }

  function callAsRootFrom(DevSystemType self, address from) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(DevSystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(DevSystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (DevSystemType) {
    return DevSystemType.wrap(resourceId.unwrap());
  }

  function getAddress(DevSystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _giveCallerTokens {
  function giveCallerTokens() external;
}

using DevSystemLib for DevSystemType global;
using DevSystemLib for CallWrapper global;
using DevSystemLib for RootCallWrapper global;
