// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ItemNFTSystem } from "../../systems/ItemNFTSystem.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { WorldContextConsumerLib } from "@latticexyz/world/src/WorldContext.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type ItemNFTSystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "ratfun", name: "ItemNFTSystem" }))
ItemNFTSystemType constant itemNFTSystem = ItemNFTSystemType.wrap(
  0x737972617466756e00000000000000004974656d4e465453797374656d000000
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title ItemNFTSystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library ItemNFTSystemLib {
  error ItemNFTSystemLib_CallingFromRootSystem();

  function exportItemToNFT(ItemNFTSystemType self, bytes32 _ratId, bytes32 _itemId) internal returns (uint256 tokenId) {
    return CallWrapper(self.toResourceId(), address(0)).exportItemToNFT(_ratId, _itemId);
  }

  function importNFTToItem(ItemNFTSystemType self, bytes32 _ratId, uint256 _tokenId) internal returns (bytes32 itemId) {
    return CallWrapper(self.toResourceId(), address(0)).importNFTToItem(_ratId, _tokenId);
  }

  function exportItemToNFT(
    CallWrapper memory self,
    bytes32 _ratId,
    bytes32 _itemId
  ) internal returns (uint256 tokenId) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ItemNFTSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_exportItemToNFT_bytes32_bytes32.exportItemToNFT, (_ratId, _itemId));

    bytes memory result = self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (uint256));
    }
  }

  function importNFTToItem(
    CallWrapper memory self,
    bytes32 _ratId,
    uint256 _tokenId
  ) internal returns (bytes32 itemId) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ItemNFTSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_importNFTToItem_bytes32_uint256.importNFTToItem, (_ratId, _tokenId));

    bytes memory result = self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (bytes32));
    }
  }

  function exportItemToNFT(
    RootCallWrapper memory self,
    bytes32 _ratId,
    bytes32 _itemId
  ) internal returns (uint256 tokenId) {
    bytes memory systemCall = abi.encodeCall(_exportItemToNFT_bytes32_bytes32.exportItemToNFT, (_ratId, _itemId));

    bytes memory result = SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (uint256));
    }
  }

  function importNFTToItem(
    RootCallWrapper memory self,
    bytes32 _ratId,
    uint256 _tokenId
  ) internal returns (bytes32 itemId) {
    bytes memory systemCall = abi.encodeCall(_importNFTToItem_bytes32_uint256.importNFTToItem, (_ratId, _tokenId));

    bytes memory result = SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (bytes32));
    }
  }

  function callFrom(ItemNFTSystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(ItemNFTSystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), WorldContextConsumerLib._msgSender());
  }

  function callAsRootFrom(ItemNFTSystemType self, address from) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(ItemNFTSystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(ItemNFTSystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (ItemNFTSystemType) {
    return ItemNFTSystemType.wrap(resourceId.unwrap());
  }

  function getAddress(ItemNFTSystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _exportItemToNFT_bytes32_bytes32 {
  function exportItemToNFT(bytes32 _ratId, bytes32 _itemId) external;
}

interface _importNFTToItem_bytes32_uint256 {
  function importNFTToItem(bytes32 _ratId, uint256 _tokenId) external;
}

using ItemNFTSystemLib for ItemNFTSystemType global;
using ItemNFTSystemLib for CallWrapper global;
using ItemNFTSystemLib for RootCallWrapper global;
