// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ManagerSystem } from "../../systems/ManagerSystem.sol";
import { Item } from "../../structs.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { WorldContextConsumerLib } from "@latticexyz/world/src/WorldContext.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type ManagerSystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "ratfun", name: "ManagerSystem" }))
ManagerSystemType constant managerSystem = ManagerSystemType.wrap(
  0x737972617466756e00000000000000004d616e6167657253797374656d000000
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title ManagerSystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library ManagerSystemLib {
  error ManagerSystemLib_CallingFromRootSystem();

  function applyOutcome(
    ManagerSystemType self,
    bytes32 _ratId,
    bytes32 _tripId,
    int256 _balanceTransferToOrFromRat,
    bytes32[] memory _itemsToRemoveFromRat,
    Item[] memory _itemsToAddToRat
  ) internal {
    return
      CallWrapper(self.toResourceId(), address(0)).applyOutcome(
        _ratId,
        _tripId,
        _balanceTransferToOrFromRat,
        _itemsToRemoveFromRat,
        _itemsToAddToRat
      );
  }

  function giveMasterKey(ManagerSystemType self, bytes32 playerId) internal {
    return CallWrapper(self.toResourceId(), address(0)).giveMasterKey(playerId);
  }

  function setWorldEvent(
    ManagerSystemType self,
    string memory cmsId,
    string memory title,
    string memory prompt,
    uint256 durationInBlocks
  ) internal {
    return CallWrapper(self.toResourceId(), address(0)).setWorldEvent(cmsId, title, prompt, durationInBlocks);
  }

  function removeWorldEvent(ManagerSystemType self) internal {
    return CallWrapper(self.toResourceId(), address(0)).removeWorldEvent();
  }

  function setCooldownCloseTrip(ManagerSystemType self, uint32 _cooldownCloseTrip) internal {
    return CallWrapper(self.toResourceId(), address(0)).setCooldownCloseTrip(_cooldownCloseTrip);
  }

  function setRatsKilledForAdminAccess(ManagerSystemType self, uint32 _ratsKilledForAdminAccess) internal {
    return CallWrapper(self.toResourceId(), address(0)).setRatsKilledForAdminAccess(_ratsKilledForAdminAccess);
  }

  function setMaxValuePerWin(ManagerSystemType self, uint32 _maxValuePerWin) internal {
    return CallWrapper(self.toResourceId(), address(0)).setMaxValuePerWin(_maxValuePerWin);
  }

  function setMinRatValueToEnter(ManagerSystemType self, uint32 _minRatValueToEnter) internal {
    return CallWrapper(self.toResourceId(), address(0)).setMinRatValueToEnter(_minRatValueToEnter);
  }

  function setTaxationLiquidateRat(ManagerSystemType self, uint32 _taxationLiquidateRat) internal {
    return CallWrapper(self.toResourceId(), address(0)).setTaxationLiquidateRat(_taxationLiquidateRat);
  }

  function setTaxationCloseTrip(ManagerSystemType self, uint32 _taxationCloseTrip) internal {
    return CallWrapper(self.toResourceId(), address(0)).setTaxationCloseTrip(_taxationCloseTrip);
  }

  function applyOutcome(
    CallWrapper memory self,
    bytes32 _ratId,
    bytes32 _tripId,
    int256 _balanceTransferToOrFromRat,
    bytes32[] memory _itemsToRemoveFromRat,
    Item[] memory _itemsToAddToRat
  ) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ManagerSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _applyOutcome_bytes32_bytes32_int256_bytes32Array_ItemArray.applyOutcome,
      (_ratId, _tripId, _balanceTransferToOrFromRat, _itemsToRemoveFromRat, _itemsToAddToRat)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function giveMasterKey(CallWrapper memory self, bytes32 playerId) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ManagerSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_giveMasterKey_bytes32.giveMasterKey, (playerId));
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function setWorldEvent(
    CallWrapper memory self,
    string memory cmsId,
    string memory title,
    string memory prompt,
    uint256 durationInBlocks
  ) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ManagerSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _setWorldEvent_string_string_string_uint256.setWorldEvent,
      (cmsId, title, prompt, durationInBlocks)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function removeWorldEvent(CallWrapper memory self) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ManagerSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_removeWorldEvent.removeWorldEvent, ());
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function setCooldownCloseTrip(CallWrapper memory self, uint32 _cooldownCloseTrip) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ManagerSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_setCooldownCloseTrip_uint32.setCooldownCloseTrip, (_cooldownCloseTrip));
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function setRatsKilledForAdminAccess(CallWrapper memory self, uint32 _ratsKilledForAdminAccess) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ManagerSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _setRatsKilledForAdminAccess_uint32.setRatsKilledForAdminAccess,
      (_ratsKilledForAdminAccess)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function setMaxValuePerWin(CallWrapper memory self, uint32 _maxValuePerWin) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ManagerSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_setMaxValuePerWin_uint32.setMaxValuePerWin, (_maxValuePerWin));
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function setMinRatValueToEnter(CallWrapper memory self, uint32 _minRatValueToEnter) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ManagerSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _setMinRatValueToEnter_uint32.setMinRatValueToEnter,
      (_minRatValueToEnter)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function setTaxationLiquidateRat(CallWrapper memory self, uint32 _taxationLiquidateRat) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ManagerSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _setTaxationLiquidateRat_uint32.setTaxationLiquidateRat,
      (_taxationLiquidateRat)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function setTaxationCloseTrip(CallWrapper memory self, uint32 _taxationCloseTrip) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ManagerSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_setTaxationCloseTrip_uint32.setTaxationCloseTrip, (_taxationCloseTrip));
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function applyOutcome(
    RootCallWrapper memory self,
    bytes32 _ratId,
    bytes32 _tripId,
    int256 _balanceTransferToOrFromRat,
    bytes32[] memory _itemsToRemoveFromRat,
    Item[] memory _itemsToAddToRat
  ) internal {
    bytes memory systemCall = abi.encodeCall(
      _applyOutcome_bytes32_bytes32_int256_bytes32Array_ItemArray.applyOutcome,
      (_ratId, _tripId, _balanceTransferToOrFromRat, _itemsToRemoveFromRat, _itemsToAddToRat)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function giveMasterKey(RootCallWrapper memory self, bytes32 playerId) internal {
    bytes memory systemCall = abi.encodeCall(_giveMasterKey_bytes32.giveMasterKey, (playerId));
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function setWorldEvent(
    RootCallWrapper memory self,
    string memory cmsId,
    string memory title,
    string memory prompt,
    uint256 durationInBlocks
  ) internal {
    bytes memory systemCall = abi.encodeCall(
      _setWorldEvent_string_string_string_uint256.setWorldEvent,
      (cmsId, title, prompt, durationInBlocks)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function removeWorldEvent(RootCallWrapper memory self) internal {
    bytes memory systemCall = abi.encodeCall(_removeWorldEvent.removeWorldEvent, ());
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function setCooldownCloseTrip(RootCallWrapper memory self, uint32 _cooldownCloseTrip) internal {
    bytes memory systemCall = abi.encodeCall(_setCooldownCloseTrip_uint32.setCooldownCloseTrip, (_cooldownCloseTrip));
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function setRatsKilledForAdminAccess(RootCallWrapper memory self, uint32 _ratsKilledForAdminAccess) internal {
    bytes memory systemCall = abi.encodeCall(
      _setRatsKilledForAdminAccess_uint32.setRatsKilledForAdminAccess,
      (_ratsKilledForAdminAccess)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function setMaxValuePerWin(RootCallWrapper memory self, uint32 _maxValuePerWin) internal {
    bytes memory systemCall = abi.encodeCall(_setMaxValuePerWin_uint32.setMaxValuePerWin, (_maxValuePerWin));
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function setMinRatValueToEnter(RootCallWrapper memory self, uint32 _minRatValueToEnter) internal {
    bytes memory systemCall = abi.encodeCall(
      _setMinRatValueToEnter_uint32.setMinRatValueToEnter,
      (_minRatValueToEnter)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function setTaxationLiquidateRat(RootCallWrapper memory self, uint32 _taxationLiquidateRat) internal {
    bytes memory systemCall = abi.encodeCall(
      _setTaxationLiquidateRat_uint32.setTaxationLiquidateRat,
      (_taxationLiquidateRat)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function setTaxationCloseTrip(RootCallWrapper memory self, uint32 _taxationCloseTrip) internal {
    bytes memory systemCall = abi.encodeCall(_setTaxationCloseTrip_uint32.setTaxationCloseTrip, (_taxationCloseTrip));
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function callFrom(ManagerSystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(ManagerSystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), WorldContextConsumerLib._msgSender());
  }

  function callAsRootFrom(ManagerSystemType self, address from) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(ManagerSystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(ManagerSystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (ManagerSystemType) {
    return ManagerSystemType.wrap(resourceId.unwrap());
  }

  function getAddress(ManagerSystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _applyOutcome_bytes32_bytes32_int256_bytes32Array_ItemArray {
  function applyOutcome(
    bytes32 _ratId,
    bytes32 _tripId,
    int256 _balanceTransferToOrFromRat,
    bytes32[] memory _itemsToRemoveFromRat,
    Item[] memory _itemsToAddToRat
  ) external;
}

interface _giveMasterKey_bytes32 {
  function giveMasterKey(bytes32 playerId) external;
}

interface _setWorldEvent_string_string_string_uint256 {
  function setWorldEvent(
    string memory cmsId,
    string memory title,
    string memory prompt,
    uint256 durationInBlocks
  ) external;
}

interface _removeWorldEvent {
  function removeWorldEvent() external;
}

interface _setCooldownCloseTrip_uint32 {
  function setCooldownCloseTrip(uint32 _cooldownCloseTrip) external;
}

interface _setRatsKilledForAdminAccess_uint32 {
  function setRatsKilledForAdminAccess(uint32 _ratsKilledForAdminAccess) external;
}

interface _setMaxValuePerWin_uint32 {
  function setMaxValuePerWin(uint32 _maxValuePerWin) external;
}

interface _setMinRatValueToEnter_uint32 {
  function setMinRatValueToEnter(uint32 _minRatValueToEnter) external;
}

interface _setTaxationLiquidateRat_uint32 {
  function setTaxationLiquidateRat(uint32 _taxationLiquidateRat) external;
}

interface _setTaxationCloseTrip_uint32 {
  function setTaxationCloseTrip(uint32 _taxationCloseTrip) external;
}

using ManagerSystemLib for ManagerSystemType global;
using ManagerSystemLib for CallWrapper global;
using ManagerSystemLib for RootCallWrapper global;
