// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { PlayerSystem } from "../../systems/PlayerSystem.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { WorldContextConsumerLib } from "@latticexyz/world/src/WorldContext.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type PlayerSystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "ratfun", name: "PlayerSystem" }))
PlayerSystemType constant playerSystem = PlayerSystemType.wrap(
  0x737972617466756e0000000000000000506c6179657253797374656d00000000
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title PlayerSystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library PlayerSystemLib {
  error PlayerSystemLib_CallingFromRootSystem();

  function spawn(PlayerSystemType self, string memory _name) internal returns (bytes32 playerId) {
    return CallWrapper(self.toResourceId(), address(0)).spawn(_name);
  }

  function balanceOf(PlayerSystemType self, bytes32 playerId) internal view returns (uint256 __auxRet0) {
    return CallWrapper(self.toResourceId(), address(0)).balanceOf(playerId);
  }

  function spawn(CallWrapper memory self, string memory _name) internal returns (bytes32 playerId) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert PlayerSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_spawn_string.spawn, (_name));

    bytes memory result = self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (bytes32));
    }
  }

  function balanceOf(CallWrapper memory self, bytes32 playerId) internal view returns (uint256 __auxRet0) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert PlayerSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_balanceOf_bytes32.balanceOf, (playerId));
    bytes memory worldCall = self.from == address(0)
      ? abi.encodeCall(IWorldCall.call, (self.systemId, systemCall))
      : abi.encodeCall(IWorldCall.callFrom, (self.from, self.systemId, systemCall));
    (bool success, bytes memory returnData) = address(_world()).staticcall(worldCall);
    if (!success) revertWithBytes(returnData);

    bytes memory result = abi.decode(returnData, (bytes));
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (uint256));
    }
  }

  function spawn(RootCallWrapper memory self, string memory _name) internal returns (bytes32 playerId) {
    bytes memory systemCall = abi.encodeCall(_spawn_string.spawn, (_name));

    bytes memory result = SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (bytes32));
    }
  }

  function balanceOf(RootCallWrapper memory self, bytes32 playerId) internal view returns (uint256 __auxRet0) {
    bytes memory systemCall = abi.encodeCall(_balanceOf_bytes32.balanceOf, (playerId));

    bytes memory result = SystemCall.staticcallOrRevert(self.from, self.systemId, systemCall);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (uint256));
    }
  }

  function callFrom(PlayerSystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(PlayerSystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), WorldContextConsumerLib._msgSender());
  }

  function callAsRootFrom(PlayerSystemType self, address from) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(PlayerSystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(PlayerSystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (PlayerSystemType) {
    return PlayerSystemType.wrap(resourceId.unwrap());
  }

  function getAddress(PlayerSystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _spawn_string {
  function spawn(string memory _name) external;
}

interface _balanceOf_bytes32 {
  function balanceOf(bytes32 playerId) external;
}

using PlayerSystemLib for PlayerSystemType global;
using PlayerSystemLib for CallWrapper global;
using PlayerSystemLib for RootCallWrapper global;
