// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { RatSystem } from "../../systems/RatSystem.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { WorldContextConsumerLib } from "@latticexyz/world/src/WorldContext.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type RatSystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "ratfun", name: "RatSystem" }))
RatSystemType constant ratSystem = RatSystemType.wrap(
  0x737972617466756e000000000000000052617453797374656d00000000000000
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title RatSystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library RatSystemLib {
  error RatSystemLib_CallingFromRootSystem();

  function createRat(RatSystemType self, string memory _name) internal returns (bytes32 ratId) {
    return CallWrapper(self.toResourceId(), address(0)).createRat(_name);
  }

  function liquidateRat(RatSystemType self) internal {
    return CallWrapper(self.toResourceId(), address(0)).liquidateRat();
  }

  function createRat(CallWrapper memory self, string memory _name) internal returns (bytes32 ratId) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert RatSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_createRat_string.createRat, (_name));

    bytes memory result = self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (bytes32));
    }
  }

  function liquidateRat(CallWrapper memory self) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert RatSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_liquidateRat.liquidateRat, ());
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function createRat(RootCallWrapper memory self, string memory _name) internal returns (bytes32 ratId) {
    bytes memory systemCall = abi.encodeCall(_createRat_string.createRat, (_name));

    bytes memory result = SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (bytes32));
    }
  }

  function liquidateRat(RootCallWrapper memory self) internal {
    bytes memory systemCall = abi.encodeCall(_liquidateRat.liquidateRat, ());
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function callFrom(RatSystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(RatSystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), WorldContextConsumerLib._msgSender());
  }

  function callAsRootFrom(RatSystemType self, address from) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(RatSystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(RatSystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (RatSystemType) {
    return RatSystemType.wrap(resourceId.unwrap());
  }

  function getAddress(RatSystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _createRat_string {
  function createRat(string memory _name) external;
}

interface _liquidateRat {
  function liquidateRat() external;
}

using RatSystemLib for RatSystemType global;
using RatSystemLib for CallWrapper global;
using RatSystemLib for RootCallWrapper global;
