// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { RoomSystem } from "../../systems/RoomSystem.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { WorldContextConsumerLib } from "@latticexyz/world/src/WorldContext.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type RoomSystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "ratfun", name: "RoomSystem" }))
RoomSystemType constant roomSystem = RoomSystemType.wrap(
  0x737972617466756e0000000000000000526f6f6d53797374656d000000000000
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title RoomSystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library RoomSystemLib {
  error RoomSystemLib_CallingFromRootSystem();

  function createRoom(
    RoomSystemType self,
    bytes32 _playerId,
    bytes32 _roomId,
    uint256 _roomCreationCost,
    uint256 _maxValuePerWin,
    uint256 _minRatValueToEnter,
    string memory _prompt
  ) internal returns (bytes32 newRoomId) {
    return
      CallWrapper(self.toResourceId(), address(0)).createRoom(
        _playerId,
        _roomId,
        _roomCreationCost,
        _maxValuePerWin,
        _minRatValueToEnter,
        _prompt
      );
  }

  function closeRoom(RoomSystemType self, bytes32 _roomId) internal {
    return CallWrapper(self.toResourceId(), address(0)).closeRoom(_roomId);
  }

  function createRoom(
    CallWrapper memory self,
    bytes32 _playerId,
    bytes32 _roomId,
    uint256 _roomCreationCost,
    uint256 _maxValuePerWin,
    uint256 _minRatValueToEnter,
    string memory _prompt
  ) internal returns (bytes32 newRoomId) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert RoomSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _createRoom_bytes32_bytes32_uint256_uint256_uint256_string.createRoom,
      (_playerId, _roomId, _roomCreationCost, _maxValuePerWin, _minRatValueToEnter, _prompt)
    );

    bytes memory result = self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (bytes32));
    }
  }

  function closeRoom(CallWrapper memory self, bytes32 _roomId) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert RoomSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_closeRoom_bytes32.closeRoom, (_roomId));
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function createRoom(
    RootCallWrapper memory self,
    bytes32 _playerId,
    bytes32 _roomId,
    uint256 _roomCreationCost,
    uint256 _maxValuePerWin,
    uint256 _minRatValueToEnter,
    string memory _prompt
  ) internal returns (bytes32 newRoomId) {
    bytes memory systemCall = abi.encodeCall(
      _createRoom_bytes32_bytes32_uint256_uint256_uint256_string.createRoom,
      (_playerId, _roomId, _roomCreationCost, _maxValuePerWin, _minRatValueToEnter, _prompt)
    );

    bytes memory result = SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (bytes32));
    }
  }

  function closeRoom(RootCallWrapper memory self, bytes32 _roomId) internal {
    bytes memory systemCall = abi.encodeCall(_closeRoom_bytes32.closeRoom, (_roomId));
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function callFrom(RoomSystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(RoomSystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), WorldContextConsumerLib._msgSender());
  }

  function callAsRootFrom(RoomSystemType self, address from) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(RoomSystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(RoomSystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (RoomSystemType) {
    return RoomSystemType.wrap(resourceId.unwrap());
  }

  function getAddress(RoomSystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _createRoom_bytes32_bytes32_uint256_uint256_uint256_string {
  function createRoom(
    bytes32 _playerId,
    bytes32 _roomId,
    uint256 _roomCreationCost,
    uint256 _maxValuePerWin,
    uint256 _minRatValueToEnter,
    string memory _prompt
  ) external;
}

interface _closeRoom_bytes32 {
  function closeRoom(bytes32 _roomId) external;
}

using RoomSystemLib for RoomSystemType global;
using RoomSystemLib for CallWrapper global;
using RoomSystemLib for RootCallWrapper global;
