// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { TripSystem } from "../../systems/TripSystem.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { WorldContextConsumerLib } from "@latticexyz/world/src/WorldContext.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type TripSystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "ratfun", name: "TripSystem" }))
TripSystemType constant tripSystem = TripSystemType.wrap(
  0x737972617466756e00000000000000005472697053797374656d000000000000
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title TripSystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library TripSystemLib {
  error TripSystemLib_CallingFromRootSystem();

  function createTrip(
    TripSystemType self,
    bytes32 _playerId,
    bytes32 _tripId,
    uint256 _tripCreationCost,
    bool _isChallengeTrip,
    uint256 _fixedMinValueToEnter,
    uint256 _overrideMaxValuePerWinPercentage,
    string memory _prompt
  ) internal returns (bytes32 newTripId) {
    return
      CallWrapper(self.toResourceId(), address(0)).createTrip(
        _playerId,
        _tripId,
        _tripCreationCost,
        _isChallengeTrip,
        _fixedMinValueToEnter,
        _overrideMaxValuePerWinPercentage,
        _prompt
      );
  }

  function addTripBalance(TripSystemType self, bytes32 _tripId, uint256 _amount) internal {
    return CallWrapper(self.toResourceId(), address(0)).addTripBalance(_tripId, _amount);
  }

  function closeTrip(TripSystemType self, bytes32 _tripId) internal {
    return CallWrapper(self.toResourceId(), address(0)).closeTrip(_tripId);
  }

  function setChallengeConfig(TripSystemType self, uint256 _minCreationCost, uint32 _activePeriodBlocks) internal {
    return CallWrapper(self.toResourceId(), address(0)).setChallengeConfig(_minCreationCost, _activePeriodBlocks);
  }

  function createTrip(
    CallWrapper memory self,
    bytes32 _playerId,
    bytes32 _tripId,
    uint256 _tripCreationCost,
    bool _isChallengeTrip,
    uint256 _fixedMinValueToEnter,
    uint256 _overrideMaxValuePerWinPercentage,
    string memory _prompt
  ) internal returns (bytes32 newTripId) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert TripSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _createTrip_bytes32_bytes32_uint256_bool_uint256_uint256_string.createTrip,
      (
        _playerId,
        _tripId,
        _tripCreationCost,
        _isChallengeTrip,
        _fixedMinValueToEnter,
        _overrideMaxValuePerWinPercentage,
        _prompt
      )
    );

    bytes memory result = self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (bytes32));
    }
  }

  function addTripBalance(CallWrapper memory self, bytes32 _tripId, uint256 _amount) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert TripSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_addTripBalance_bytes32_uint256.addTripBalance, (_tripId, _amount));
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function closeTrip(CallWrapper memory self, bytes32 _tripId) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert TripSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_closeTrip_bytes32.closeTrip, (_tripId));
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function setChallengeConfig(CallWrapper memory self, uint256 _minCreationCost, uint32 _activePeriodBlocks) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert TripSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _setChallengeConfig_uint256_uint32.setChallengeConfig,
      (_minCreationCost, _activePeriodBlocks)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function createTrip(
    RootCallWrapper memory self,
    bytes32 _playerId,
    bytes32 _tripId,
    uint256 _tripCreationCost,
    bool _isChallengeTrip,
    uint256 _fixedMinValueToEnter,
    uint256 _overrideMaxValuePerWinPercentage,
    string memory _prompt
  ) internal returns (bytes32 newTripId) {
    bytes memory systemCall = abi.encodeCall(
      _createTrip_bytes32_bytes32_uint256_bool_uint256_uint256_string.createTrip,
      (
        _playerId,
        _tripId,
        _tripCreationCost,
        _isChallengeTrip,
        _fixedMinValueToEnter,
        _overrideMaxValuePerWinPercentage,
        _prompt
      )
    );

    bytes memory result = SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (bytes32));
    }
  }

  function addTripBalance(RootCallWrapper memory self, bytes32 _tripId, uint256 _amount) internal {
    bytes memory systemCall = abi.encodeCall(_addTripBalance_bytes32_uint256.addTripBalance, (_tripId, _amount));
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function closeTrip(RootCallWrapper memory self, bytes32 _tripId) internal {
    bytes memory systemCall = abi.encodeCall(_closeTrip_bytes32.closeTrip, (_tripId));
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function setChallengeConfig(
    RootCallWrapper memory self,
    uint256 _minCreationCost,
    uint32 _activePeriodBlocks
  ) internal {
    bytes memory systemCall = abi.encodeCall(
      _setChallengeConfig_uint256_uint32.setChallengeConfig,
      (_minCreationCost, _activePeriodBlocks)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function callFrom(TripSystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(TripSystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), WorldContextConsumerLib._msgSender());
  }

  function callAsRootFrom(TripSystemType self, address from) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(TripSystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(TripSystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (TripSystemType) {
    return TripSystemType.wrap(resourceId.unwrap());
  }

  function getAddress(TripSystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _createTrip_bytes32_bytes32_uint256_bool_uint256_uint256_string {
  function createTrip(
    bytes32 _playerId,
    bytes32 _tripId,
    uint256 _tripCreationCost,
    bool _isChallengeTrip,
    uint256 _fixedMinValueToEnter,
    uint256 _overrideMaxValuePerWinPercentage,
    string memory _prompt
  ) external;
}

interface _addTripBalance_bytes32_uint256 {
  function addTripBalance(bytes32 _tripId, uint256 _amount) external;
}

interface _closeTrip_bytes32 {
  function closeTrip(bytes32 _tripId) external;
}

interface _setChallengeConfig_uint256_uint32 {
  function setChallengeConfig(uint256 _minCreationCost, uint32 _activePeriodBlocks) external;
}

using TripSystemLib for TripSystemType global;
using TripSystemLib for CallWrapper global;
using TripSystemLib for RootCallWrapper global;
