// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { UnlockAdminSystem } from "../../systems/UnlockAdminSystem.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { WorldContextConsumerLib } from "@latticexyz/world/src/WorldContext.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type UnlockAdminSystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "ratfun", name: "UnlockAdminSyste" }))
UnlockAdminSystemType constant unlockAdminSystem = UnlockAdminSystemType.wrap(
  0x737972617466756e0000000000000000556e6c6f636b41646d696e5379737465
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title UnlockAdminSystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library UnlockAdminSystemLib {
  error UnlockAdminSystemLib_CallingFromRootSystem();

  function unlockAdmin(UnlockAdminSystemType self) internal {
    return CallWrapper(self.toResourceId(), address(0)).unlockAdmin();
  }

  function unlockAdmin(CallWrapper memory self) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert UnlockAdminSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_unlockAdmin.unlockAdmin, ());
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function unlockAdmin(RootCallWrapper memory self) internal {
    bytes memory systemCall = abi.encodeCall(_unlockAdmin.unlockAdmin, ());
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function callFrom(UnlockAdminSystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(UnlockAdminSystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), WorldContextConsumerLib._msgSender());
  }

  function callAsRootFrom(UnlockAdminSystemType self, address from) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(UnlockAdminSystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(UnlockAdminSystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (UnlockAdminSystemType) {
    return UnlockAdminSystemType.wrap(resourceId.unwrap());
  }

  function getAddress(UnlockAdminSystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _unlockAdmin {
  function unlockAdmin() external;
}

using UnlockAdminSystemLib for UnlockAdminSystemType global;
using UnlockAdminSystemLib for CallWrapper global;
using UnlockAdminSystemLib for RootCallWrapper global;
