// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IBrainSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IBrainSystem {
  function ratroom__createBrain(
    uint32 traitA,
    uint32 traitB,
    uint32 traitC,
    uint32 traitD
  ) external returns (bytes32 playerEntity);
}
