// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IDevSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IDevSystem {
  function ratroom__givePlayerBalance(bytes32 _playerId, uint256 _amount) external;

  function ratroom__removePlayerBalance(bytes32 _playerId) external;

  function ratroom__createRoomAsAdmin(
    string memory _roomName,
    string memory _roomPrompt,
    bytes32 _roomLevel,
    uint256 _extraBalance
  ) external returns (bytes32 roomId);

  function ratroom__destroyRoomAsAdmin(bytes32 _roomId) external;

  function ratroom__updateLevel(
    bytes32 _levelId,
    uint256 _levelMinBalance,
    uint256 _levelMaxBalance,
    uint256 _roomCreationCost
  ) external;

  function ratroom__addRoomBalance(bytes32 _roomId) external;
}
