// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IItemNFTSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IItemNFTSystem {
  function ratfun__exportItemToNFT(bytes32 _ratId, bytes32 _itemId) external returns (uint256 tokenId);

  function ratfun__importNFTToItem(bytes32 _ratId, uint256 _tokenId) external returns (bytes32 itemId);
}
