// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IManagerSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IManagerSystem {
  function ratroom__addItemToLoadOut(
    bytes32 _ratId,
    string memory _name,
    int256 _value
  ) external returns (bytes32 itemId);

  function ratroom__removeItemFromLoadOut(bytes32 _ratId, bytes32 _itemId) external;

  function ratroom__addTraitToRat(
    bytes32 _ratId,
    string memory _name,
    int256 _value
  ) external returns (bytes32 traitId);

  function ratroom__removeTraitFromRat(bytes32 _ratId, bytes32 _traitId) external;

  function ratroom__increaseBalance(bytes32 _id, uint256 _change) external;

  function ratroom__decreaseBalance(bytes32 _id, uint256 _change) external;

  function ratroom__increaseHealth(bytes32 _ratId, uint256 _change) external;

  function ratroom__decreaseHealth(bytes32 _ratId, uint256 _change) external;
}
