// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Item } from "../../structs.sol";

/**
 * @title IManagerSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IManagerSystem {
  function ratfun__applyOutcome(
    bytes32 _ratId,
    bytes32 _tripId,
    int256 _balanceTransferToOrFromRat,
    bytes32[] calldata _itemsToRemoveFromRat,
    Item[] calldata _itemsToAddToRat
  ) external;

  function ratfun__giveMasterKey(bytes32 playerId) external;

  function ratfun__setWorldEvent(
    string memory cmsId,
    string memory title,
    string memory prompt,
    uint256 durationInBlocks
  ) external;

  function ratfun__removeWorldEvent() external;

  function ratfun__setCooldownCloseTrip(uint32 _cooldownCloseTrip) external;

  function ratfun__setRatsKilledForAdminAccess(uint32 _ratsKilledForAdminAccess) external;

  function ratfun__setMaxValuePerWin(uint32 _maxValuePerWin) external;

  function ratfun__setMinRatValueToEnter(uint32 _minRatValueToEnter) external;

  function ratfun__setTaxationLiquidateRat(uint32 _taxationLiquidateRat) external;

  function ratfun__setTaxationCloseTrip(uint32 _taxationCloseTrip) external;
}
