// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IPlayerSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IPlayerSystem {
  function ratroom__spawn(string memory _name) external returns (bytes32 _playerId);

  function ratroom__transferBalanceToRat(uint256 _value) external;

  function ratroom__transferBalanceToPlayer(uint256 _value) external;

  function ratroom__transferItemToInventory(bytes32 _itemId) external;

  function ratroom__transferItemToLoadOut(bytes32 _itemId) external;
}
