// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IRatSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IRatSystem {
  function ratroom__createRat(string calldata _name) external returns (bytes32 ratId);

  function ratroom__liquidateRat(bytes32 _ratId) external;

  function ratroom__dropItem(bytes32 _itemId) external;
}
