// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IRoomSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IRoomSystem {
  function ratroom__createRoom(
    bytes32 _playerId,
    bytes32 _levelId,
    bytes32 _roomId,
    string memory _prompt
  ) external returns (bytes32 newRoomId);

  function ratroom__closeRoom(bytes32 _roomId) external;
}
