// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ITripSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ITripSystem {
  function ratfun__createTrip(
    bytes32 _playerId,
    bytes32 _tripId,
    uint256 _tripCreationCost,
    string memory _prompt
  ) external returns (bytes32 newTripId);

  function ratfun__addTripBalance(bytes32 _tripId, uint256 _amount) external;

  function ratfun__closeTrip(bytes32 _tripId) external;
}
