// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/codegen/interfaces/IBaseWorld.sol";
import { IDevSystem } from "./IDevSystem.sol";
import { IManagerSystem } from "./IManagerSystem.sol";
import { IPlayerSystem } from "./IPlayerSystem.sol";
import { IRatSystem } from "./IRatSystem.sol";
import { IRoomSystem } from "./IRoomSystem.sol";

/**
 * @title IWorld
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @notice This interface integrates all systems and associated function selectors
 * that are dynamically registered in the World during deployment.
 * @dev This is an autogenerated file; do not edit manually.
 */
interface IWorld is IBaseWorld, IDevSystem, IManagerSystem, IPlayerSystem, IRatSystem, IRoomSystem {}
