/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Outcome = {
  _id: string
  _type: "outcome"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  worldAddress?: string
  playerId?: string
  playerName?: string
  tripId?: string
  tripIndex?: number
  ratId?: string
  ratName?: string
  log?: Array<{
    timestamp?: string
    event?: string
    _key: string
  }>
  balanceTransfers?: Array<{
    logStep?: number
    amount?: number
    _key: string
  }>
  itemChanges?: Array<{
    name?: string
    logStep?: number
    type?: string
    value?: number
    id?: string
    _key: string
  }>
  itemsLostOnDeath?: Array<{
    name?: string
    value?: number
    id?: string
    _key: string
  }>
  inventoryOnEntrance?: Array<{
    name?: string
    value?: number
    id?: string
    _key: string
  }>
  oldTripValue?: number
  tripValueChange?: number
  tripValue?: number
  oldRatValue?: number
  ratValueChange?: number
  ratValue?: number
  oldRatBalance?: number
  newRatBalance?: number
  debuggingInfo?: string
  logOutput?: string
  mainProcessingTime?: number
  slug?: Slug
}

export type Slug = {
  _type: "slug"
  current?: string
  source?: string
}

export type TestPrompts = {
  _id: string
  _type: "testPrompts"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  eventPromptA?: {
    _ref: string
    _type: "reference"
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: "prompt"
  }
  eventPromptB?: {
    _ref: string
    _type: "reference"
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: "prompt"
  }
  correctionPromptA?: {
    _ref: string
    _type: "reference"
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: "prompt"
  }
  correctionPromptB?: {
    _ref: string
    _type: "reference"
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: "prompt"
  }
}

export type ActivePrompts = {
  _id: string
  _type: "activePrompts"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  activeEventPrompt?: {
    _ref: string
    _type: "reference"
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: "prompt"
  }
  activeCorrectionPrompt?: {
    _ref: string
    _type: "reference"
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: "prompt"
  }
}

export type Prompt = {
  _id: string
  _type: "prompt"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  prompt?: Markdown
  returnFormat?: Code
}

export type Code = {
  _type: "code"
  language?: string
  filename?: string
  code?: string
  highlightedLines?: Array<number>
}

export type Markdown = string

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch"
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: "sanity.imagePalette"
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions"
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata"
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot"
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SanityImageCrop = {
  _type: "sanity.imageCrop"
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityFileAsset = {
  _id: string
  _type: "sanity.fileAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData"
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: "sanity.imageAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: "geopoint"
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | Outcome
  | Slug
  | TestPrompts
  | ActivePrompts
  | Prompt
  | Code
  | Markdown
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
export declare const internalGroqTypeReferenceTo: unique symbol
