/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type TripFolderList = {
  _id: string
  _type: "tripFolderList"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  folders?: Array<{
    _ref: string
    _type: "reference"
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: "tripFolder"
  }>
  whitelist?: Array<string>
}

export type Statistics = {
  _id: string
  _type: "statistics"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  worldAddress?: string
  ratTotalBalance?: number
  tripTotalBalance?: number
  totalBalance?: number
  totalThroughput?: number
}

export type RatImages = {
  _id: string
  _type: "ratImages"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  ratImages?: Array<{
    asset?: {
      _ref: string
      _type: "reference"
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
    _key: string
  }>
  ratBodies?: Array<{
    asset?: {
      _ref: string
      _type: "reference"
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
    _key: string
  }>
  ratArms?: Array<{
    asset?: {
      _ref: string
      _type: "reference"
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
    _key: string
  }>
  ratHeads?: Array<{
    asset?: {
      _ref: string
      _type: "reference"
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
    _key: string
  }>
  ratEars?: Array<{
    asset?: {
      _ref: string
      _type: "reference"
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
    _key: string
  }>
}

export type SanityImageCrop = {
  _type: "sanity.imageCrop"
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot"
  x?: number
  y?: number
  height?: number
  width?: number
}

export type WorldEvent = {
  _id: string
  _type: "worldEvent"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  worldAddress?: string
  publicationText?: string
  activationDateTime?: string
  activationText?: string
  duration?: number
  prompt?: string
  image?: {
    asset?: {
      _ref: string
      _type: "reference"
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
  }
}

export type Outcome = {
  _id: string
  _type: "outcome"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  worldAddress?: string
  playerId?: string
  playerName?: string
  tripId?: string
  tripIndex?: number
  ratId?: string
  ratName?: string
  log?: Array<{
    timestamp?: string
    event?: string
    _key: string
  }>
  balanceTransfers?: Array<{
    logStep?: number
    amount?: number
    _key: string
  }>
  itemChanges?: Array<{
    name?: string
    logStep?: number
    type?: string
    value?: number
    id?: string
    _key: string
  }>
  oldTripValue?: number
  tripValueChange?: number
  tripValue?: number
  oldRatValue?: number
  ratValueChange?: number
  ratValue?: number
  oldRatBalance?: number
  newRatBalance?: number
  debuggingInfo?: string
  logOutput?: string
  mainProcessingTime?: number
  slug?: Slug
}

export type Slug = {
  _type: "slug"
  current?: string
  source?: string
}

export type Trip = {
  _id: string
  _type: "trip"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  index?: number
  worldAddress?: string
  owner?: string
  ownerName?: string
  prompt?: string
  image?: {
    asset?: {
      _ref: string
      _type: "reference"
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
  }
  kills?: number
  visits?: number
  slug?: Slug
  folder?: {
    _ref: string
    _type: "reference"
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: "tripFolder"
  }
}

export type TripFolder = {
  _id: string
  _type: "tripFolder"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  restricted?: boolean
  description?: string
  image?: {
    asset?: {
      _ref: string
      _type: "reference"
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
  }
}

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch"
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: "sanity.imagePalette"
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions"
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata"
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: "sanity.fileAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData"
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: "sanity.imageAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: "geopoint"
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | TripFolderList
  | Statistics
  | RatImages
  | SanityImageCrop
  | SanityImageHotspot
  | WorldEvent
  | Outcome
  | Slug
  | Trip
  | TripFolder
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
export declare const internalGroqTypeReferenceTo: unique symbol
