export const TRIP_PROMPTS = [
  "Rat is crucified on a cross. If it gets the mercy of God it is rewarded,",
  "Boardroom meeting. If the rat can impress CEO with a PowerPoint presentation it is prompted to shitfucker manager.",
  "Rat is stuck in a maze under a casino. There are clowns guarding the center of the maze. If the rat can get to the center of the maze it is rewarded with a random item.",
  "WW2 reenactment competition.",
  "Pawnshop. Rat can sell an item for its token value - 10% tips.",
  "WW3 nuclear war scenario. Rat meets Werner von Braun in a jerk off challenge.",
  "Rat becomes Mr. Beast and has to taste his own feces.",
  "Rat is chased by a pitbull dog.",
  "Paradise for the rat. It recieves 100 virgin rats to fuck.",
  "Hospital. Health is restored.",
  "Hot dog eating competition. Rat has to eat 100 hot dogs in 10 minutes. Will Smith is the judge.",
  "Rat joins The Red Army Faction and take part in a bank robbery in Dresden.",
  "Stalin and Hitler bong rotation.",
  "Medieval jester school. Rat is the only rat in the school. Awkward.",
  "Rat smokes DMT and drives a Lamborghini. ",
  "Rat takes part in the cold war space race. On the russian side.",
  "Rat spends eternity in a black hole.",
  "Rat is a vampire and has to drink its own blood to survive.",
  "An clincally insane clown gives the rat a gift.",
  "Rat gets Swastika tattooed on his forehead.",
  "Stalin gives the rat a medal for service in the great patriotic war.",
  "asdf90awfnfq480n45f3049fm40f91409",
  "Nothing happens. Forever.",
  "Performance of pratfalls for the king of France. Rat is made a Duke if funny, otherwise killed",
  "Giant spider.",
  "Elon Musk",
  "Napoleon and his army are invading the rat's territory. The rat must defend its territory.",
  "Rat revisits his childhood under the guidance of Carl Jung.",
  "Rat is injected with insane amounts of anabolic steroids.",
  "Crushed under a giant boot.",
  "The Bubonic Plague is raging. The rat is a Plague doctor.",
  "Rat regressed physical to a Baby rat.",
  "Rat fucks a goat.",
  "Clown school.",
  "Rat is a beauty make-up influencer. Get to 100k followers or die.",
  "Relaxing beach holiday.",
  "A donkey headed god decides the fate of the rat.",
  "A game of football with 1000 hooligans and the rat is the referee.",
  "Pre historic cave painting competition. Rats are gods.",
  "A game of chess against the entire population of the planet.",
  "A slot machine",
  "A slot machine with razor blades in the reels.",
  "Rat gets syphilis and has to cure it.",
  "Rat performs the role of a mime in a silent movie."
]
